// えいたんごクイズ - 単語帳データ
// Generated: 2026/4/5 15:13:00
window.WORKLISTS = {
  "TOEIC_Day01": [
    {word:"英単語",meaning:"和訳"},
    {word:"available",meaning:"利用可能な・入手できる"},
    {word:"schedule",meaning:"スケジュール・予定を組む"},
    {word:"provide",meaning:"提供する・与える"},
    {word:"require",meaning:"必要とする・要求する"},
    {word:"confirm",meaning:"確認する・承認する"},
    {word:"meeting",meaning:"会議・ミーティング"},
    {word:"invoice",meaning:"請求書・インボイス"},
    {word:"deadline",meaning:"締め切り・期限"},
    {word:"submit",meaning:"提出する・申し込む"},
    {word:"approve",meaning:"承認する・賛成する"},
    {word:"department",meaning:"部署・部門"},
    {word:"contract",meaning:"契約・契約書"},
    {word:"client",meaning:"顧客・依頼人"},
    {word:"proposal",meaning:"提案書・企画書"},
    {word:"budget",meaning:"予算・予算を立てる"},
    {word:"report",meaning:"報告書・報告する"},
    {word:"estimate",meaning:"見積もり・推定する"},
    {word:"inventory",meaning:"在庫・棚卸し"},
    {word:"itinerary",meaning:"旅程・旅行日程"},
    {word:"conference",meaning:"会議・学会"},
    {word:"shipment",meaning:"出荷・発送・荷物"},
    {word:"postpone",meaning:"延期する・後回しにする"},
    {word:"appointment",meaning:"予約・約束・任命"},
    {word:"headquarters",meaning:"本社・本部"},
    {word:"negotiate",meaning:"交渉する・折衝する"},
    {word:"promotion",meaning:"昇進・販売促進"},
    {word:"reimburse",meaning:"払い戻す・弁償する"},
    {word:"purchase",meaning:"購入・購入する"},
    {word:"efficient",meaning:"効率的な・有能な"},
    {word:"revenue",meaning:"収益・収入・売上"},
    {word:"personnel",meaning:"人事部門・職員"},
    {word:"maintenance",meaning:"維持・保守・整備"},
    {word:"warranty",meaning:"保証・保証書"},
    {word:"facility",meaning:"施設・設備・機能"},
    {word:"collaborate",meaning:"協力する・共同作業する"},
    {word:"implement",meaning:"実施する・実行する"},
    {word:"delegate",meaning:"委任する・代表者"},
    {word:"comply",meaning:"従う・応じる・準拠する"},
    {word:"outstanding",meaning:"未払いの・優れた"},
    {word:"agenda",meaning:"議題・議事日程"},
    {word:"quarterly",meaning:"四半期ごとの・季刊の"},
    {word:"fiscal",meaning:"財政上の・会計年度の"},
    {word:"launch",meaning:"発売する・立ち上げる"},
    {word:"retail",meaning:"小売・小売の"},
    {word:"wholesale",meaning:"卸売・卸売の"},
    {word:"audit",meaning:"監査・会計検査"},
    {word:"profit",meaning:"利益・利潤・収益"},
    {word:"deficit",meaning:"赤字・不足・欠損"},
    {word:"surplus",meaning:"余剰・黒字・過剰"},
    {word:"turnover",meaning:"売上高・離職率"},
    {word:"marketing",meaning:"マーケティング・市場調査"},
    {word:"strategy",meaning:"戦略・方針・計画"},
    {word:"campaign",meaning:"キャンペーン・宣伝活動"},
    {word:"brochure",meaning:"パンフレット・小冊子"},
    {word:"advertisement",meaning:"広告・宣伝"},
    {word:"feedback",meaning:"フィードバック・意見"},
    {word:"presentation",meaning:"プレゼンテーション・発表"},
    {word:"productivity",meaning:"生産性・生産力"},
    {word:"performance",meaning:"業績・パフォーマンス"},
    {word:"recruitment",meaning:"採用活動・募集"},
    {word:"compensation",meaning:"補償・報酬・賃金"},
    {word:"deduction",meaning:"控除・差し引き"},
    {word:"payroll",meaning:"給与名簿・給与支払い"},
    {word:"pension",meaning:"年金・恩給・退職金"},
    {word:"resignation",meaning:"辞職・辞表・辞任"},
    {word:"termination",meaning:"終了・解雇・契約解除"},
    {word:"probation",meaning:"試用期間・仮採用"},
    {word:"supervisor",meaning:"上司・監督者・管理者"},
    {word:"colleague",meaning:"同僚・仕事仲間"},
    {word:"branch",meaning:"支店・支社・枝"},
    {word:"merger",meaning:"合併・統合する"},
    {word:"acquisition",meaning:"買収・取得・習得"},
    {word:"shareholder",meaning:"株主・出資者"},
    {word:"dividend",meaning:"配当・配当金"},
    {word:"asset",meaning:"資産・財産・強み"},
    {word:"liability",meaning:"負債・責任・義務"},
    {word:"receipt",meaning:"領収書・受取・レシート"},
    {word:"transaction",meaning:"取引・業務・取引行為"},
    {word:"deposit",meaning:"預金・保証金・預ける"},
    {word:"withdrawal",meaning:"引き出し・撤退・撤回"},
    {word:"currency",meaning:"通貨・外貨・貨幣"},
    {word:"mortgage",meaning:"住宅ローン・抵当"},
    {word:"franchise",meaning:"フランチャイズ・特権"},
    {word:"trademark",meaning:"商標・ブランド"},
    {word:"patent",meaning:"特許・特許権"},
    {word:"copyright",meaning:"著作権・版権"},
    {word:"regulation",meaning:"規制・規則・法規"},
    {word:"compliance",meaning:"コンプライアンス・法令遵守"},
    {word:"legislation",meaning:"法律・立法・法制"},
    {word:"amendment",meaning:"修正・改正・修正案"},
    {word:"penalty",meaning:"罰則・ペナルティ・罰金"},
    {word:"dispatch",meaning:"発送する・派遣する"},
    {word:"freight",meaning:"貨物・運賃・運送"},
    {word:"customs",meaning:"税関・関税・慣習"},
    {word:"tariff",meaning:"関税・料金表"},
    {word:"logistics",meaning:"物流・ロジスティクス"},
    {word:"warehouse",meaning:"倉庫・貯蔵庫"},
    {word:"distribution",meaning:"流通・配布・分配"},
    {word:"supplier",meaning:"供給業者・仕入れ先"},
    {word:"vendor",meaning:"ベンダー・販売業者"}
  ],
  "TOEIC_Day02": [
    {word:"英単語",meaning:"和訳"},
    {word:"procurement",meaning:"調達・購買・入手"},
    {word:"outsource",meaning:"外部委託する"},
    {word:"infrastructure",meaning:"インフラ・基盤設備"},
    {word:"renovation",meaning:"改修・リノベーション"},
    {word:"premises",meaning:"建物・敷地・前提"},
    {word:"lease",meaning:"賃貸契約・リース・貸す"},
    {word:"tenant",meaning:"テナント・借家人"},
    {word:"landlord",meaning:"家主・地主・オーナー"},
    {word:"utilities",meaning:"公共料金・光熱費"},
    {word:"insurance",meaning:"保険・保険契約"},
    {word:"coverage",meaning:"保険範囲・報道"},
    {word:"premium",meaning:"保険料・プレミアム"},
    {word:"claim",meaning:"保険請求・主張する"},
    {word:"shortage",meaning:"不足・欠乏・不足分"},
    {word:"demand",meaning:"需要・要求する"},
    {word:"supply",meaning:"供給・供給する・在庫"},
    {word:"competition",meaning:"競争・競合・競争相手"},
    {word:"consumer",meaning:"消費者・顧客・利用者"},
    {word:"satisfaction",meaning:"満足・充足・満足感"},
    {word:"loyalty",meaning:"忠誠心・ロイヤルティ"},
    {word:"referral",meaning:"紹介・推薦・紹介状"},
    {word:"incentive",meaning:"インセンティブ・動機"},
    {word:"bonus",meaning:"ボーナス・特典"},
    {word:"commission",meaning:"コミッション・手数料"},
    {word:"quota",meaning:"割り当て・ノルマ"},
    {word:"target",meaning:"目標・ターゲット・的"},
    {word:"forecast",meaning:"予測・予報する・見通し"},
    {word:"analysis",meaning:"分析・解析・分析結果"},
    {word:"statistics",meaning:"統計・統計学"},
    {word:"survey",meaning:"調査・アンケート"},
    {word:"questionnaire",meaning:"アンケート・質問票"},
    {word:"benchmark",meaning:"基準・ベンチマーク・指標"},
    {word:"evaluation",meaning:"評価・査定・評価結果"},
    {word:"assessment",meaning:"評価・アセスメント・査定"},
    {word:"appraisal",meaning:"査定・評価・鑑定"},
    {word:"objective",meaning:"目標・客観的な・目的"},
    {word:"priority",meaning:"優先事項・優先度"},
    {word:"initiative",meaning:"イニシアチブ・主導権"},
    {word:"feasibility",meaning:"実現可能性・妥当性"},
    {word:"prototype",meaning:"試作品・プロトタイプ"},
    {word:"milestone",meaning:"マイルストーン・節目"},
    {word:"timeline",meaning:"タイムライン・年表"},
    {word:"workforce",meaning:"労働力・従業員"},
    {word:"talent",meaning:"才能・人材・有能な人"},
    {word:"expertise",meaning:"専門知識・専門性"},
    {word:"proficiency",meaning:"熟練・習熟度・能力"},
    {word:"credential",meaning:"資格・証明書"},
    {word:"qualification",meaning:"資格・条件・能力"},
    {word:"internship",meaning:"インターンシップ・研修"},
    {word:"seminar",meaning:"セミナー・講習会"},
    {word:"workshop",meaning:"ワークショップ・研修会"},
    {word:"symposium",meaning:"シンポジウム・討論会"},
    {word:"keynote",meaning:"基調講演・キーノート"},
    {word:"attendee",meaning:"出席者・参加者"},
    {word:"venue",meaning:"会場・開催地"},
    {word:"reservation",meaning:"予約・保留"},
    {word:"hospitality",meaning:"おもてなし・接待・歓待"},
    {word:"accommodation",meaning:"宿泊・宿泊施設"},
    {word:"commute",meaning:"通勤・通学・通勤する"},
    {word:"relocate",meaning:"移転する・転勤する"},
    {word:"transfer",meaning:"転勤・移動・移送する"},
    {word:"downsizing",meaning:"人員削減・縮小・合理化"},
    {word:"restructuring",meaning:"リストラ・再編・組織改革"},
    {word:"layoff",meaning:"一時解雇・レイオフ"},
    {word:"severance",meaning:"退職金・解雇補償"},
    {word:"redundancy",meaning:"余剰人員・人員整理"},
    {word:"consolidation",meaning:"統合・合併・強化"},
    {word:"subsidiary",meaning:"子会社・補助的な"},
    {word:"affiliate",meaning:"関連会社・提携する"},
    {word:"stakeholder",meaning:"ステークホルダー・利害関係者"},
    {word:"equity",meaning:"株主資本・公平・持分"},
    {word:"portfolio",meaning:"ポートフォリオ・資産構成"},
    {word:"indicator",meaning:"指標・インジケーター"},
    {word:"metric",meaning:"指標・測定基準・尺度"},
    {word:"KPI",meaning:"重要業績評価指標"},
    {word:"ROI",meaning:"投資収益率・費用対効果"},
    {word:"gross",meaning:"総計の・粗利益・全体の"},
    {word:"net",meaning:"純利益・正味の・純粋な"},
    {word:"overhead",meaning:"間接費・オーバーヘッド"},
    {word:"expenditure",meaning:"支出・費用・出費"},
    {word:"allocation",meaning:"割り当て・配分"},
    {word:"subsidy",meaning:"補助金・助成金"},
    {word:"grant",meaning:"助成金・付与する・許可する"},
    {word:"rebate",meaning:"リベート・払い戻し・割引"},
    {word:"markup",meaning:"値上げ・マークアップ・利幅"},
    {word:"margin",meaning:"利幅・マージン・余白"},
    {word:"breakeven",meaning:"損益分岐点"},
    {word:"cashflow",meaning:"キャッシュフロー"},
    {word:"liquidity",meaning:"流動性・換金性"},
    {word:"solvency",meaning:"支払い能力・債務支払能力"},
    {word:"bankruptcy",meaning:"破産・倒産・破綻"},
    {word:"insolvency",meaning:"支払い不能・倒産"},
    {word:"authorization",meaning:"承認・許可・認可"},
    {word:"certification",meaning:"認定・証明・資格取得"},
    {word:"accreditation",meaning:"認証・資格認定・公認"},
    {word:"verification",meaning:"確認・検証・認証"},
    {word:"validation",meaning:"検証・妥当性確認・有効化"},
    {word:"authentication",meaning:"認証・本人確認"},
    {word:"memorandum",meaning:"覚書・メモ・社内連絡文"},
    {word:"correspondence",meaning:"文書往来・書簡・通信"}
  ],
  "TOEIC_Day05": [
    {word:"英単語",meaning:"和訳"},
    {word:"niche market",meaning:"ニッチ市場・隙間市場"},
    {word:"market research",meaning:"市場調査・マーケットリサーチ"},
    {word:"focus group",meaning:"フォーカスグループ・座談会"},
    {word:"customer journey",meaning:"カスタマージャーニー"},
    {word:"conversion rate",meaning:"コンバージョン率・成約率"},
    {word:"lead generation",meaning:"リード獲得・見込み客開拓"},
    {word:"prospect",meaning:"見込み客・展望・可能性"},
    {word:"pitch",meaning:"売り込み・プレゼン・ピッチ"},
    {word:"cold call",meaning:"コールドコール・飛び込み電話"},
    {word:"follow-up",meaning:"フォローアップ・追跡・連絡"},
    {word:"negotiation",meaning:"交渉・折衝・ネゴシエーション"},
    {word:"closing",meaning:"クロージング・成約・締め"},
    {word:"upsell",meaning:"アップセル・上位商品への誘導"},
    {word:"cross-sell",meaning:"クロスセル・関連商品の販売"},
    {word:"retention",meaning:"顧客維持・保持・定着"},
    {word:"churn rate",meaning:"解約率・離脱率"},
    {word:"net promoter score",meaning:"NPS・顧客推薦度"},
    {word:"customer satisfaction",meaning:"顧客満足度"},
    {word:"word of mouth",meaning:"口コミ・口頭での宣伝"},
    {word:"testimonial",meaning:"推薦状・証言・体験談"},
    {word:"endorsement",meaning:"推薦・承認・支持"},
    {word:"sponsorship",meaning:"スポンサーシップ・協賛"},
    {word:"affiliate marketing",meaning:"アフィリエイトマーケティング"},
    {word:"email marketing",meaning:"メールマーケティング"},
    {word:"content marketing",meaning:"コンテンツマーケティング"},
    {word:"social media",meaning:"ソーシャルメディア・SNS"},
    {word:"digital marketing",meaning:"デジタルマーケティング"},
    {word:"SEO",meaning:"検索エンジン最適化"},
    {word:"pay-per-click",meaning:"PPC・クリック課金広告"},
    {word:"impression",meaning:"インプレッション・印象・表示回数"},
    {word:"click-through rate",meaning:"クリック率・CTR"},
    {word:"engagement",meaning:"エンゲージメント・関与"},
    {word:"viral",meaning:"バイラル・口コミで広まる"},
    {word:"influencer",meaning:"インフルエンサー・影響力のある人"},
    {word:"A/B testing",meaning:"A/Bテスト・比較試験"},
    {word:"personalization",meaning:"パーソナライゼーション・個人化"},
    {word:"funnel",meaning:"ファネル・販売経路"},
    {word:"pipeline",meaning:"パイプライン・案件管理"},
    {word:"CRM",meaning:"顧客関係管理"},
    {word:"ERP",meaning:"基幹業務システム"},
    {word:"SaaS",meaning:"サービスとしてのソフトウェア"},
    {word:"cloud computing",meaning:"クラウドコンピューティング"},
    {word:"subscription",meaning:"サブスクリプション・定期購読"},
    {word:"pricing strategy",meaning:"価格戦略・プライシング"},
    {word:"discount",meaning:"割引・値引き・ディスカウント"},
    {word:"coupon",meaning:"クーポン・割引券"},
    {word:"voucher",meaning:"バウチャー・商品券"},
    {word:"loyalty program",meaning:"ロイヤルティプログラム"},
    {word:"membership",meaning:"会員制度・メンバーシップ"},
    {word:"recurring revenue",meaning:"定期収益・継続収益"},
    {word:"ARR",meaning:"年間定期収益"},
    {word:"MRR",meaning:"月次定期収益"},
    {word:"lifetime value",meaning:"顧客生涯価値・LTV"},
    {word:"customer acquisition cost",meaning:"顧客獲得コスト・CAC"},
    {word:"return on ad spend",meaning:"広告費用対効果・ROAS"},
    {word:"market share",meaning:"市場シェア・市場占有率"},
    {word:"competitive advantage",meaning:"競争優位性・差別化"},
    {word:"value proposition",meaning:"価値提案"},
    {word:"unique selling point",meaning:"独自の強み・USP"},
    {word:"product differentiation",meaning:"製品差別化"},
    {word:"commodity",meaning:"コモディティ・日用品"},
    {word:"price sensitivity",meaning:"価格感応度"},
    {word:"elasticity",meaning:"弾力性・価格弾力性"},
    {word:"supply and demand",meaning:"需要と供給"},
    {word:"market penetration",meaning:"市場浸透・普及"},
    {word:"market development",meaning:"市場開拓"},
    {word:"product development",meaning:"製品開発"},
    {word:"diversification",meaning:"多角化・多様化"},
    {word:"vertical integration",meaning:"垂直統合"},
    {word:"horizontal integration",meaning:"水平統合"},
    {word:"economies of scale",meaning:"規模の経済・スケールメリット"},
    {word:"offshoring",meaning:"オフショアリング・海外委託"},
    {word:"nearshoring",meaning:"ニアショアリング・近隣国への委託"},
    {word:"just-in-time",meaning:"ジャストインタイム"},
    {word:"lean manufacturing",meaning:"リーン生産・無駄のない製造"},
    {word:"agile",meaning:"アジャイル・機敏な・柔軟な"},
    {word:"scrum",meaning:"スクラム・アジャイル開発手法"},
    {word:"kanban",meaning:"カンバン・在庫管理方式"},
    {word:"six sigma",meaning:"シックスシグマ・品質管理手法"},
    {word:"kaizen",meaning:"改善・カイゼン"},
    {word:"global supply chain",meaning:"グローバルサプライチェーン"},
    {word:"value chain",meaning:"バリューチェーン"},
    {word:"benchmark comparison",meaning:"ベンチマーク比較"},
    {word:"competitive analysis",meaning:"競合分析"},
    {word:"SWOT analysis",meaning:"SWOT分析"},
    {word:"market entry strategy",meaning:"市場参入戦略"},
    {word:"go-to-market",meaning:"市場投入戦略・GTM"},
    {word:"product launch",meaning:"製品発売・ローンチ"},
    {word:"brand awareness",meaning:"ブランド認知度"},
    {word:"accounting",meaning:"会計・経理・アカウンティング"},
    {word:"bookkeeping",meaning:"簿記・帳簿管理"},
    {word:"ledger",meaning:"元帳・台帳・会計帳簿"},
    {word:"journal",meaning:"仕訳帳・日記・日誌"},
    {word:"debit",meaning:"借方・引き落とし"},
    {word:"credit",meaning:"貸方・信用・クレジット"},
    {word:"accrued",meaning:"発生した・未払いの・累積した"},
    {word:"prepaid",meaning:"前払いの・前払い済みの"},
    {word:"receivable",meaning:"売掛金・受取手形"},
    {word:"payable",meaning:"支払うべき・買掛金"},
    {word:"debt",meaning:"負債・借金・債務"}
  ],
  "TOEIC_Day04": [
    {word:"英単語",meaning:"和訳"},
    {word:"mentoring",meaning:"メンタリング・指導・支援"},
    {word:"coaching",meaning:"コーチング・指導・育成"},
    {word:"performance review",meaning:"業績評価・人事評価"},
    {word:"demotion",meaning:"降格・降職"},
    {word:"dismissal",meaning:"解雇・免職・却下"},
    {word:"outplacement",meaning:"再就職支援"},
    {word:"grievance",meaning:"苦情・不満・不平"},
    {word:"mediation",meaning:"調停・仲介・和解"},
    {word:"arbitration",meaning:"仲裁・調停"},
    {word:"litigation",meaning:"訴訟・争訟・法的手続き"},
    {word:"settlement",meaning:"和解・決済・清算"},
    {word:"benefits",meaning:"福利厚生・手当・恩恵"},
    {word:"allowance",meaning:"手当・許容量"},
    {word:"reimbursement",meaning:"払い戻し・経費精算"},
    {word:"overtime",meaning:"残業・時間外労働"},
    {word:"flextime",meaning:"フレックスタイム・弾力勤務"},
    {word:"telecommute",meaning:"テレワーク・在宅勤務"},
    {word:"remote work",meaning:"リモートワーク・在宅勤務"},
    {word:"workload",meaning:"作業量・業務量・仕事の負担"},
    {word:"empowerment",meaning:"エンパワーメント・権限付与"},
    {word:"diversity",meaning:"多様性・ダイバーシティ"},
    {word:"inclusion",meaning:"インクルージョン・包括"},
    {word:"harassment",meaning:"ハラスメント・嫌がらせ"},
    {word:"discrimination",meaning:"差別・識別・区別"},
    {word:"whistleblower",meaning:"内部告発者"},
    {word:"confidentiality",meaning:"機密性・守秘義務"},
    {word:"non-disclosure",meaning:"秘密保持・非開示"},
    {word:"intellectual property",meaning:"知的財産権"},
    {word:"trade secret",meaning:"企業秘密・営業秘密"},
    {word:"non-compete",meaning:"競業避止・非競争"},
    {word:"severance pay",meaning:"退職金・解雇手当"},
    {word:"exit interview",meaning:"退職面談・離職面接"},
    {word:"reference",meaning:"推薦状・参照・参考"},
    {word:"background check",meaning:"身元調査"},
    {word:"probationary period",meaning:"試用期間"},
    {word:"permanent position",meaning:"正社員・常勤職"},
    {word:"temporary position",meaning:"派遣社員・一時的な職"},
    {word:"part-time",meaning:"パートタイム・非常勤"},
    {word:"full-time",meaning:"フルタイム・常勤"},
    {word:"freelance",meaning:"フリーランス・自由契約"},
    {word:"contractor",meaning:"請負業者・コントラクター"},
    {word:"subcontractor",meaning:"下請け業者"},
    {word:"consultant",meaning:"コンサルタント・顧問"},
    {word:"specialist",meaning:"専門家・スペシャリスト"},
    {word:"generalist",meaning:"ゼネラリスト・万能型人材"},
    {word:"executive",meaning:"経営幹部・役員"},
    {word:"manager",meaning:"マネージャー・管理者"},
    {word:"director",meaning:"ディレクター・取締役"},
    {word:"vice president",meaning:"副社長・副会長"},
    {word:"CEO",meaning:"最高経営責任者"},
    {word:"CFO",meaning:"最高財務責任者"},
    {word:"COO",meaning:"最高執行責任者"},
    {word:"board of directors",meaning:"取締役会"},
    {word:"annual general meeting",meaning:"株主総会・年次総会"},
    {word:"fiscal year",meaning:"会計年度・事業年度"},
    {word:"earnings report",meaning:"業績報告・決算報告書"},
    {word:"annual report",meaning:"年次報告書"},
    {word:"balance sheet",meaning:"貸借対照表"},
    {word:"income statement",meaning:"損益計算書"},
    {word:"cash flow statement",meaning:"キャッシュフロー計算書"},
    {word:"profit and loss",meaning:"損益・損益計算"},
    {word:"accounts receivable",meaning:"売掛金・未収金"},
    {word:"accounts payable",meaning:"買掛金・未払金"},
    {word:"depreciation",meaning:"減価償却・価値の下落"},
    {word:"amortization",meaning:"償却・分割払い"},
    {word:"accrual",meaning:"発生主義・未収計上"},
    {word:"reconciliation",meaning:"照合・一致・和解"},
    {word:"audit trail",meaning:"監査証跡・取引記録"},
    {word:"internal control",meaning:"内部統制・内部管理"},
    {word:"due diligence",meaning:"デューデリジェンス・適正評価"},
    {word:"compliance audit",meaning:"コンプライアンス監査"},
    {word:"succession planning",meaning:"後継者計画"},
    {word:"leadership development",meaning:"リーダーシップ開発"},
    {word:"performance metrics",meaning:"パフォーマンス指標"},
    {word:"organizational chart",meaning:"組織図"},
    {word:"job description",meaning:"職務記述書・JD"},
    {word:"competency framework",meaning:"コンピテンシーフレームワーク"},
    {word:"360-degree feedback",meaning:"360度フィードバック"},
    {word:"goal setting",meaning:"目標設定"},
    {word:"SMART goals",meaning:"SMART目標"},
    {word:"OKR",meaning:"目標と主要成果"},
    {word:"individual development plan",meaning:"個人開発計画・IDP"},
    {word:"career path",meaning:"キャリアパス"},
    {word:"job rotation",meaning:"ジョブローテーション"},
    {word:"talent pool",meaning:"タレントプール・人材候補リスト"},
    {word:"succession candidate",meaning:"後継者候補"},
    {word:"high-potential employee",meaning:"ハイポテンシャル従業員"},
    {word:"employee engagement",meaning:"従業員エンゲージメント"},
    {word:"corporate culture",meaning:"企業文化・組織文化"},
    {word:"work-life balance",meaning:"ワークライフバランス"},
    {word:"employee satisfaction",meaning:"従業員満足度"},
    {word:"retention strategy",meaning:"人材定着戦略"},
    {word:"talent management",meaning:"タレントマネジメント"},
    {word:"human resources",meaning:"人事・人的資源"},
    {word:"brand",meaning:"ブランド・商標・銘柄"},
    {word:"branding",meaning:"ブランディング・ブランド構築"},
    {word:"positioning",meaning:"ポジショニング・位置づけ"},
    {word:"segmentation",meaning:"セグメンテーション・市場細分化"},
    {word:"demographics",meaning:"人口統計・市場特性"},
    {word:"target market",meaning:"ターゲット市場・対象市場"}
  ],
  "TOEIC_Day06": [
    {word:"英単語",meaning:"和訳"},
    {word:"bond",meaning:"債券・社債・保証"},
    {word:"stock",meaning:"株式・株・在庫"},
    {word:"share",meaning:"株式・配分・シェア"},
    {word:"index",meaning:"指数・インデックス・索引"},
    {word:"hedge",meaning:"ヘッジ・リスク回避"},
    {word:"futures",meaning:"先物取引・将来の"},
    {word:"options",meaning:"オプション・選択権"},
    {word:"derivative",meaning:"デリバティブ・派生商品"},
    {word:"arbitrage",meaning:"裁定取引・アービトラージ"},
    {word:"capital",meaning:"資本・資金・首都"},
    {word:"venture capital",meaning:"ベンチャーキャピタル"},
    {word:"private equity",meaning:"プライベートエクイティ"},
    {word:"initial public offering",meaning:"新規株式公開・IPO"},
    {word:"securities",meaning:"有価証券・証券"},
    {word:"forex",meaning:"外国為替・FX"},
    {word:"interest rate",meaning:"金利・利子率"},
    {word:"inflation",meaning:"インフレ・物価上昇"},
    {word:"deflation",meaning:"デフレ・物価下落"},
    {word:"recession",meaning:"景気後退・不況"},
    {word:"GDP",meaning:"国内総生産"},
    {word:"trade balance",meaning:"貿易収支"},
    {word:"fiscal policy",meaning:"財政政策"},
    {word:"monetary policy",meaning:"金融政策"},
    {word:"quantitative easing",meaning:"量的緩和・QE"},
    {word:"central bank",meaning:"中央銀行"},
    {word:"interest",meaning:"利子・利息・興味"},
    {word:"principal",meaning:"元金・主要な・校長"},
    {word:"collateral",meaning:"担保・保証物件"},
    {word:"guarantee",meaning:"保証・保証する"},
    {word:"indemnity",meaning:"損害賠償・補償"},
    {word:"escrow",meaning:"エスクロー・第三者預託"},
    {word:"fiduciary",meaning:"受託者・信任の"},
    {word:"trust",meaning:"信託・信頼・信用"},
    {word:"annuity",meaning:"年金・定期支払い"},
    {word:"lump sum",meaning:"一括払い・まとめ払い"},
    {word:"installment",meaning:"分割払い・割賦"},
    {word:"refinance",meaning:"借り換え・リファイナンス"},
    {word:"default",meaning:"デフォルト・債務不履行"},
    {word:"foreclosure",meaning:"差し押さえ・競売"},
    {word:"liquidation",meaning:"清算・資産売却"},
    {word:"receivership",meaning:"管財・管理受託"},
    {word:"write-off",meaning:"帳消し・損失計上"},
    {word:"provision",meaning:"引当金・準備金・規定"},
    {word:"reserve",meaning:"準備金・予備・積立"},
    {word:"retained earnings",meaning:"内部留保・利益剰余金"},
    {word:"capital gain",meaning:"キャピタルゲイン・売却益"},
    {word:"capital loss",meaning:"キャピタルロス・売却損"},
    {word:"tax",meaning:"税・課税する"},
    {word:"tax deduction",meaning:"税控除・税額控除"},
    {word:"tax credit",meaning:"税額控除"},
    {word:"tax return",meaning:"確定申告・税金の還付"},
    {word:"withholding tax",meaning:"源泉徴収税"},
    {word:"value added tax",meaning:"付加価値税・VAT"},
    {word:"corporate tax",meaning:"法人税"},
    {word:"income tax",meaning:"所得税"},
    {word:"capital gains tax",meaning:"譲渡所得税"},
    {word:"inheritance tax",meaning:"相続税"},
    {word:"property tax",meaning:"固定資産税"},
    {word:"duty",meaning:"関税・義務・任務"},
    {word:"exemption",meaning:"免除・控除・非課税"},
    {word:"net worth",meaning:"純資産・純資産価値"},
    {word:"working capital",meaning:"運転資本・運転資金"},
    {word:"leverage",meaning:"レバレッジ・財務的梃子"},
    {word:"hedging",meaning:"ヘッジング・リスク回避"},
    {word:"asset allocation",meaning:"資産配分"},
    {word:"risk tolerance",meaning:"リスク許容度"},
    {word:"yield",meaning:"利回り・収益率"},
    {word:"coupon rate",meaning:"クーポンレート・利率"},
    {word:"maturity",meaning:"満期・償還期"},
    {word:"volatility",meaning:"ボラティリティ・変動性"},
    {word:"credit rating",meaning:"信用格付け"},
    {word:"investment grade",meaning:"投資適格"},
    {word:"junk bond",meaning:"ジャンク債・高利回り債"},
    {word:"government bond",meaning:"国債"},
    {word:"corporate bond",meaning:"社債"},
    {word:"money market",meaning:"マネーマーケット"},
    {word:"treasury bill",meaning:"国庫短期証券"},
    {word:"certificate of deposit",meaning:"譲渡性預金・CD"},
    {word:"fixed deposit",meaning:"定期預金"},
    {word:"current account",meaning:"当座預金"},
    {word:"savings account",meaning:"普通預金口座"},
    {word:"checking account",meaning:"当座預金口座"},
    {word:"bank account",meaning:"銀行口座"},
    {word:"wire transfer",meaning:"電信送金"},
    {word:"letter of credit",meaning:"信用状・L/C"},
    {word:"performance bond",meaning:"履行保証"},
    {word:"supply chain",meaning:"サプライチェーン・供給連鎖"},
    {word:"sourcing",meaning:"ソーシング・調達先選定"},
    {word:"purchase order",meaning:"発注書・購買注文"},
    {word:"delivery",meaning:"配達・配送・納品"},
    {word:"cargo",meaning:"貨物・積み荷"},
    {word:"consignment",meaning:"委託・委託品・積荷"},
    {word:"manifest",meaning:"積荷目録・マニフェスト"},
    {word:"bill of lading",meaning:"船荷証券・B/L"},
    {word:"customs clearance",meaning:"通関手続き"},
    {word:"import",meaning:"輸入・輸入する"},
    {word:"export",meaning:"輸出・輸出する"},
    {word:"trade",meaning:"貿易・取引する"},
    {word:"embargo",meaning:"禁輸措置・輸出禁止"},
    {word:"free trade",meaning:"自由貿易"}
  ],
  "TOEIC_Day03": [
    {word:"英単語",meaning:"和訳"},
    {word:"notification",meaning:"通知・知らせ・告知"},
    {word:"announcement",meaning:"発表・告知・アナウンス"},
    {word:"circular",meaning:"回覧・通達・循環する"},
    {word:"bulletin",meaning:"掲示・速報・公報"},
    {word:"newsletter",meaning:"ニュースレター・社内報"},
    {word:"press release",meaning:"プレスリリース・報道発表"},
    {word:"minutes",meaning:"議事録・議事録を取る"},
    {word:"resolution",meaning:"決議・解決・決意"},
    {word:"motion",meaning:"動議・動き・提案"},
    {word:"quorum",meaning:"定足数・クォーラム"},
    {word:"proxy",meaning:"代理・委任状"},
    {word:"ratify",meaning:"批准する・承認する"},
    {word:"endorse",meaning:"承認する・署名する"},
    {word:"confidential",meaning:"機密の・極秘の・内密の"},
    {word:"proprietary",meaning:"専有の・社有の・独占的な"},
    {word:"disclosure",meaning:"開示・発覚・情報公開"},
    {word:"transparency",meaning:"透明性・透明・明瞭"},
    {word:"accountability",meaning:"説明責任・責任"},
    {word:"integrity",meaning:"誠実・完全性・整合性"},
    {word:"ethics",meaning:"倫理・道徳・倫理観"},
    {word:"governance",meaning:"ガバナンス・統治・管理"},
    {word:"protocol",meaning:"プロトコル・議定書・手順"},
    {word:"procedure",meaning:"手順・手続き・方法"},
    {word:"guideline",meaning:"ガイドライン・指針"},
    {word:"policy",meaning:"方針・政策・ポリシー"},
    {word:"manual",meaning:"マニュアル・手引き・手動の"},
    {word:"template",meaning:"テンプレート・ひな形・型"},
    {word:"format",meaning:"フォーマット・形式・書式"},
    {word:"layout",meaning:"レイアウト・配置・設計"},
    {word:"draft",meaning:"草案・下書き・下書きする"},
    {word:"revise",meaning:"改訂する・修正する・見直す"},
    {word:"proofread",meaning:"校正する・校閲する"},
    {word:"publish",meaning:"発行する・公表する・出版する"},
    {word:"circulate",meaning:"回覧する・流通する"},
    {word:"forward",meaning:"転送する・前進する"},
    {word:"archive",meaning:"アーカイブ・保存する"},
    {word:"retrieve",meaning:"取り出す・検索する"},
    {word:"database",meaning:"データベース・データ集積"},
    {word:"spreadsheet",meaning:"スプレッドシート・表計算"},
    {word:"software",meaning:"ソフトウェア・プログラム"},
    {word:"hardware",meaning:"ハードウェア・機器"},
    {word:"network",meaning:"ネットワーク・ネットワーク化"},
    {word:"server",meaning:"サーバー・給仕人"},
    {word:"bandwidth",meaning:"帯域幅・通信容量"},
    {word:"firewall",meaning:"ファイアウォール・防火壁"},
    {word:"encryption",meaning:"暗号化・暗号"},
    {word:"password",meaning:"パスワード・合言葉"},
    {word:"backup",meaning:"バックアップ・予備・控え"},
    {word:"update",meaning:"更新する・最新情報"},
    {word:"upgrade",meaning:"アップグレード・改善"},
    {word:"installation",meaning:"インストール・設置"},
    {word:"configuration",meaning:"設定・構成・形態"},
    {word:"compatibility",meaning:"互換性・適合性"},
    {word:"integration",meaning:"統合・結合・融合"},
    {word:"interface",meaning:"インターフェース・接点"},
    {word:"functionality",meaning:"機能性・機能・実用性"},
    {word:"specification",meaning:"仕様・仕様書・明細"},
    {word:"troubleshoot",meaning:"トラブルシューティング"},
    {word:"diagnostic",meaning:"診断の・診断テスト"},
    {word:"malfunction",meaning:"誤作動・機能不全"},
    {word:"breakdown",meaning:"故障・崩壊・内訳"},
    {word:"downtime",meaning:"ダウンタイム・稼働停止"},
    {word:"outage",meaning:"停電・サービス停止"},
    {word:"restoration",meaning:"復旧・回復・修復"},
    {word:"scalability",meaning:"スケーラビリティ・拡張性"},
    {word:"efficiency",meaning:"効率・効率性・能率"},
    {word:"optimization",meaning:"最適化・オプティマイゼーション"},
    {word:"automation",meaning:"自動化・オートメーション"},
    {word:"digitalization",meaning:"デジタル化・デジタル変革"},
    {word:"innovation",meaning:"イノベーション・革新"},
    {word:"disruption",meaning:"混乱・破壊的イノベーション"},
    {word:"transformation",meaning:"変革・変化・転換"},
    {word:"sustainability",meaning:"持続可能性・サステナビリティ"},
    {word:"rollout",meaning:"展開・実施・ロールアウト"},
    {word:"deployment",meaning:"展開・配備・デプロイ"},
    {word:"implementation",meaning:"実施・実装・導入"},
    {word:"adoption",meaning:"採用・導入・適応"},
    {word:"transition",meaning:"移行・移行期間"},
    {word:"migration",meaning:"移行・移転・マイグレーション"},
    {word:"collaboration",meaning:"コラボレーション・共同作業"},
    {word:"partnership",meaning:"パートナーシップ・提携"},
    {word:"alliance",meaning:"アライアンス・同盟・連携"},
    {word:"outsourcing",meaning:"外部委託・アウトソーシング"},
    {word:"pilot program",meaning:"試験的プログラム・試験計画"},
    {word:"change management",meaning:"変革管理・チェンジマネジメント"},
    {word:"project management",meaning:"プロジェクト管理"},
    {word:"risk management",meaning:"リスク管理"},
    {word:"contingency plan",meaning:"緊急時対応計画"},
    {word:"business continuity",meaning:"事業継続・BCP"},
    {word:"disaster recovery",meaning:"災害復旧・障害復旧"},
    {word:"business intelligence",meaning:"ビジネスインテリジェンス・BI"},
    {word:"dashboard",meaning:"ダッシュボード"},
    {word:"analytics",meaning:"アナリティクス・分析"},
    {word:"data-driven",meaning:"データドリブン・データに基づく"},
    {word:"real-time",meaning:"リアルタイム・即時の"},
    {word:"digital transformation",meaning:"デジタルトランスフォーメーション・DX"},
    {word:"headhunting",meaning:"ヘッドハンティング・引き抜き"},
    {word:"onboarding",meaning:"オンボーディング・新入社員研修"},
    {word:"orientation",meaning:"オリエンテーション・方向付け"},
    {word:"training",meaning:"トレーニング・研修・訓練"}
  ],
  "TOEIC_Day14": [
    {word:"英単語",meaning:"和訳"},
    {word:"digital twin",meaning:"デジタルツイン"},
    {word:"preventive maintenance",meaning:"予防保全"},
    {word:"corrective maintenance",meaning:"事後保全"},
    {word:"mean time between failures",meaning:"平均故障間隔・MTBF"},
    {word:"mean time to repair",meaning:"平均修理時間・MTTR"},
    {word:"availability",meaning:"稼働率・可用性"},
    {word:"reliability",meaning:"信頼性"},
    {word:"durability",meaning:"耐久性"},
    {word:"field service",meaning:"フィールドサービス"},
    {word:"spare parts",meaning:"スペアパーツ・交換部品"},
    {word:"obsolescence",meaning:"陳腐化・旧式化"},
    {word:"end of life",meaning:"製品終了・廃止"},
    {word:"product recall",meaning:"製品回収・リコール"},
    {word:"safety standard",meaning:"安全基準"},
    {word:"environmental regulation",meaning:"環境規制"},
    {word:"waste management",meaning:"廃棄物管理"},
    {word:"carbon emissions",meaning:"炭素排出量"},
    {word:"energy consumption",meaning:"エネルギー消費"},
    {word:"green manufacturing",meaning:"グリーン製造"},
    {word:"ESG",meaning:"環境・社会・ガバナンス"},
    {word:"process documentation",meaning:"プロセス文書化"},
    {word:"quality management system",meaning:"品質管理システム・QMS"},
    {word:"ISO 9001",meaning:"ISO9001品質管理規格"},
    {word:"CAPA",meaning:"是正・予防措置"},
    {word:"deviation",meaning:"逸脱・外れ"},
    {word:"out-of-specification",meaning:"規格外・OOS"},
    {word:"investigation report",meaning:"調査報告書"},
    {word:"batch record",meaning:"製造記録"},
    {word:"change control",meaning:"変更管理"},
    {word:"validation protocol",meaning:"バリデーション計画書"},
    {word:"GMP",meaning:"適正製造規範"},
    {word:"GLP",meaning:"適正試験所規範"},
    {word:"GCP",meaning:"適正臨床規範"},
    {word:"cleanroom",meaning:"クリーンルーム"},
    {word:"sterile manufacturing",meaning:"無菌製造"},
    {word:"aseptic process",meaning:"無菌プロセス"},
    {word:"contamination control",meaning:"汚染管理"},
    {word:"particulate testing",meaning:"微粒子試験"},
    {word:"environmental monitoring",meaning:"環境モニタリング"},
    {word:"risk assessment",meaning:"リスク評価・アセスメント"},
    {word:"failure mode analysis",meaning:"故障モード解析・FMEA"},
    {word:"root cause analysis",meaning:"根本原因分析・RCA"},
    {word:"corrective action",meaning:"是正措置"},
    {word:"preventive action",meaning:"予防措置"},
    {word:"supplier qualification",meaning:"サプライヤー資格審査"},
    {word:"supplier audit",meaning:"サプライヤー監査"},
    {word:"approved supplier list",meaning:"承認サプライヤーリスト"},
    {word:"pharmaceutical",meaning:"製薬・医薬品"},
    {word:"healthcare",meaning:"医療・ヘルスケア"},
    {word:"medical device",meaning:"医療機器"},
    {word:"clinical trial",meaning:"臨床試験"},
    {word:"drug approval",meaning:"新薬承認"},
    {word:"FDA",meaning:"米国食品医薬品局"},
    {word:"regulatory submission",meaning:"規制当局申請"},
    {word:"prescription",meaning:"処方箋・処方する"},
    {word:"over-the-counter",meaning:"市販薬・処方箋不要"},
    {word:"generic drug",meaning:"ジェネリック医薬品"},
    {word:"patent expiry",meaning:"特許期限切れ"},
    {word:"biosimilar",meaning:"バイオシミラー"},
    {word:"vaccine",meaning:"ワクチン"},
    {word:"immunization",meaning:"免疫化・予防接種"},
    {word:"health insurance",meaning:"健康保険・医療保険"},
    {word:"copayment",meaning:"自己負担分・コペイ"},
    {word:"deductible insurance",meaning:"医療保険の控除額"},
    {word:"network provider",meaning:"ネットワーク加入医療機関"},
    {word:"out-of-network",meaning:"ネットワーク外"},
    {word:"preauthorization",meaning:"事前承認"},
    {word:"billing",meaning:"請求・医療費請求"},
    {word:"insurance claim",meaning:"保険請求"},
    {word:"diagnosis",meaning:"診断"},
    {word:"treatment",meaning:"治療・処置"},
    {word:"prognosis",meaning:"予後・見通し"},
    {word:"symptom",meaning:"症状"},
    {word:"chronic disease",meaning:"慢性疾患"},
    {word:"acute condition",meaning:"急性疾患"},
    {word:"preventive care",meaning:"予防医療"},
    {word:"wellness program",meaning:"ウェルネスプログラム"},
    {word:"occupational health",meaning:"産業保健"},
    {word:"ergonomics",meaning:"人間工学・エルゴノミクス"},
    {word:"workplace safety",meaning:"職場安全"},
    {word:"OSHA",meaning:"労働安全衛生局"},
    {word:"personal protective equipment",meaning:"個人防護具・PPE"},
    {word:"first aid",meaning:"応急処置・救急手当"},
    {word:"emergency response",meaning:"緊急対応"},
    {word:"incident report",meaning:"事故報告書"},
    {word:"pharmacovigilance",meaning:"医薬品安全性監視"},
    {word:"post-marketing surveillance",meaning:"市販後調査"},
    {word:"adverse event",meaning:"有害事象"},
    {word:"side effect",meaning:"副作用"},
    {word:"clinical data management",meaning:"臨床データ管理"},
    {word:"electronic data capture",meaning:"電子データ収集・EDC"},
    {word:"laboratory information management",meaning:"LIMS"},
    {word:"electronic batch record",meaning:"電子製造記録・eBR"},
    {word:"21 CFR Part 11",meaning:"電子記録・電子署名規制"},
    {word:"supply chain integrity",meaning:"サプライチェーン完全性"},
    {word:"cold chain management",meaning:"コールドチェーン管理"},
    {word:"packaging compliance",meaning:"包装コンプライアンス"},
    {word:"labeling regulation",meaning:"ラベル規制"},
    {word:"serialization compliance",meaning:"シリアル化コンプライアンス"},
    {word:"bioequivalence",meaning:"生物学的同等性"}
  ],
  "TOEIC_Day10": [
    {word:"英単語",meaning:"和訳"},
    {word:"non-compete agreement",meaning:"競業避止契約"},
    {word:"employment contract",meaning:"雇用契約書"},
    {word:"service agreement",meaning:"サービス契約"},
    {word:"license agreement",meaning:"ライセンス契約"},
    {word:"franchise agreement",meaning:"フランチャイズ契約"},
    {word:"purchase agreement",meaning:"売買契約書"},
    {word:"memorandum of understanding",meaning:"覚書・MOU"},
    {word:"letter of intent",meaning:"意向書・LOI"},
    {word:"term sheet",meaning:"タームシート・基本条件書"},
    {word:"closing documents",meaning:"クロージング書類"},
    {word:"title transfer",meaning:"所有権移転"},
    {word:"deed of sale",meaning:"売買証書"},
    {word:"promissory note",meaning:"約束手形"},
    {word:"power of attorney",meaning:"委任状"},
    {word:"notarization",meaning:"公証・公証する"},
    {word:"apostille",meaning:"アポスティーユ・認証"},
    {word:"trademark registration",meaning:"商標登録"},
    {word:"patent application",meaning:"特許出願"},
    {word:"copyright protection",meaning:"著作権保護"},
    {word:"infringement",meaning:"侵害"},
    {word:"royalty",meaning:"使用料・ロイヤリティ"},
    {word:"licensing fee",meaning:"ライセンス料"},
    {word:"regulatory compliance",meaning:"規制遵守"},
    {word:"anti-money laundering",meaning:"マネーロンダリング防止・AML"},
    {word:"know your customer",meaning:"顧客確認・KYC"},
    {word:"data protection",meaning:"データ保護"},
    {word:"privacy policy",meaning:"プライバシーポリシー"},
    {word:"GDPR",meaning:"一般データ保護規則"},
    {word:"data breach",meaning:"データ漏洩・情報流出"},
    {word:"cybersecurity",meaning:"サイバーセキュリティ"},
    {word:"phishing",meaning:"フィッシング詐欺"},
    {word:"fraud",meaning:"詐欺・不正"},
    {word:"embezzlement",meaning:"横領・着服"},
    {word:"bribery",meaning:"贈収賄・賄賂"},
    {word:"corruption",meaning:"汚職・腐敗"},
    {word:"whistleblowing",meaning:"内部告発"},
    {word:"corporate governance",meaning:"コーポレートガバナンス"},
    {word:"fiduciary duty",meaning:"受託者責任"},
    {word:"conflict of interest",meaning:"利益相反"},
    {word:"insider trading",meaning:"インサイダー取引"},
    {word:"market manipulation",meaning:"相場操縦"},
    {word:"antitrust",meaning:"独占禁止・反トラスト"},
    {word:"merger review",meaning:"合併審査"},
    {word:"regulatory approval",meaning:"規制当局の承認"},
    {word:"due process",meaning:"適正手続き"},
    {word:"class action",meaning:"集団訴訟"},
    {word:"injunction",meaning:"差し止め命令"},
    {word:"subpoena",meaning:"召喚状・証拠提出命令"},
    {word:"deposition",meaning:"陳述・証拠"},
    {word:"discovery",meaning:"証拠開示手続き"},
    {word:"affidavit",meaning:"宣誓供述書"},
    {word:"statute of limitations",meaning:"時効・出訴期限"},
    {word:"estoppel",meaning:"禁反言・エストッペル"},
    {word:"indemnity clause",meaning:"免責条項"},
    {word:"waiver",meaning:"権利放棄・免除"},
    {word:"consent decree",meaning:"同意審決"},
    {word:"injunctive relief",meaning:"差し止め救済"},
    {word:"declaratory judgment",meaning:"確認判決"},
    {word:"specific performance",meaning:"特定履行"},
    {word:"liquidated damages",meaning:"違約金・損害賠償額の予定"},
    {word:"punitive damages",meaning:"懲罰的損害賠償"},
    {word:"consequential damages",meaning:"結果的損害賠償"},
    {word:"negligence",meaning:"過失・怠慢"},
    {word:"strict liability",meaning:"厳格責任・無過失責任"},
    {word:"product liability",meaning:"製造物責任"},
    {word:"tort",meaning:"不法行為"},
    {word:"contract law",meaning:"契約法"},
    {word:"commercial law",meaning:"商法"},
    {word:"corporate law",meaning:"会社法"},
    {word:"labor law",meaning:"労働法"},
    {word:"Basel III",meaning:"バーゼルIII・国際金融規制"},
    {word:"capital adequacy ratio",meaning:"自己資本比率"},
    {word:"tier 1 capital",meaning:"Tier1資本"},
    {word:"leverage ratio",meaning:"レバレッジ比率"},
    {word:"liquidity coverage ratio",meaning:"流動性カバレッジ比率"},
    {word:"net stable funding ratio",meaning:"安定調達比率・NSFR"},
    {word:"systemic risk",meaning:"システミックリスク"},
    {word:"too big to fail",meaning:"大きすぎて潰せない"},
    {word:"bailout",meaning:"救済・公的支援"},
    {word:"tapering",meaning:"テーパリング・量的緩和縮小"},
    {word:"interest rate hike",meaning:"利上げ"},
    {word:"rate cut",meaning:"利下げ"},
    {word:"negative interest rate",meaning:"マイナス金利"},
    {word:"yield curve",meaning:"利回り曲線"},
    {word:"inverted yield curve",meaning:"逆イールドカーブ"},
    {word:"forward guidance",meaning:"フォワードガイダンス"},
    {word:"inflation targeting",meaning:"インフレターゲット"},
    {word:"price stability",meaning:"物価安定"},
    {word:"financial stability",meaning:"金融安定"},
    {word:"macroprudential",meaning:"マクロプルーデンシャル"},
    {word:"bid-ask spread",meaning:"ビッドアスクスプレッド"},
    {word:"market depth",meaning:"市場の深さ・流動性"},
    {word:"order book",meaning:"注文帳・気配値一覧"},
    {word:"limit order",meaning:"指値注文"},
    {word:"market order",meaning:"成行注文"},
    {word:"stop loss",meaning:"ストップロス・損切り"},
    {word:"take profit",meaning:"テイクプロフィット・利確"},
    {word:"margin trading",meaning:"信用取引"},
    {word:"short selling",meaning:"空売り"},
    {word:"long position",meaning:"ロングポジション・買い持ち"}
  ],
  "TOEIC_Day09": [
    {word:"英単語",meaning:"和訳"},
    {word:"passport",meaning:"パスポート・旅券"},
    {word:"visa",meaning:"ビザ・査証"},
    {word:"immigration",meaning:"入国管理・移民"},
    {word:"transit",meaning:"通過・乗り継ぎ"},
    {word:"jet lag",meaning:"時差ぼけ"},
    {word:"convention",meaning:"コンベンション・大会・慣行"},
    {word:"exhibition",meaning:"展示会・エキシビション"},
    {word:"trade show",meaning:"商談会・見本市"},
    {word:"expo",meaning:"博覧会・エキスポ"},
    {word:"summit",meaning:"サミット・首脳会談"},
    {word:"forum",meaning:"フォーラム・討論会"},
    {word:"event planning",meaning:"イベント計画・企画"},
    {word:"event management",meaning:"イベント管理"},
    {word:"catering",meaning:"ケータリング・料理サービス"},
    {word:"audiovisual",meaning:"視聴覚・AV機器"},
    {word:"speaker",meaning:"スピーカー・講演者"},
    {word:"moderator",meaning:"司会者・モデレーター"},
    {word:"panel discussion",meaning:"パネルディスカッション"},
    {word:"breakout session",meaning:"分科会・ブレイクアウト"},
    {word:"networking",meaning:"ネットワーキング・人脈形成"},
    {word:"registration",meaning:"登録・受付・参加申込"},
    {word:"badge",meaning:"バッジ・名札"},
    {word:"exhibitor",meaning:"出展者・展示者"},
    {word:"booth",meaning:"ブース・展示ブース"},
    {word:"handout",meaning:"配布資料・ハンドアウト"},
    {word:"program",meaning:"プログラム・日程"},
    {word:"invitation",meaning:"招待状・招待"},
    {word:"RSVP",meaning:"出欠返信・出席確認"},
    {word:"attendance",meaning:"出席・参加・出勤"},
    {word:"virtual event",meaning:"オンラインイベント"},
    {word:"webinar",meaning:"ウェビナー・オンラインセミナー"},
    {word:"livestream",meaning:"ライブストリーム・生配信"},
    {word:"hybrid event",meaning:"ハイブリッドイベント"},
    {word:"Q&A session",meaning:"質疑応答"},
    {word:"team building",meaning:"チームビルディング"},
    {word:"incentive trip",meaning:"インセンティブトリップ"},
    {word:"corporate retreat",meaning:"企業合宿・研修旅行"},
    {word:"gala dinner",meaning:"ガラディナー・祝賀晩餐会"},
    {word:"award ceremony",meaning:"表彰式"},
    {word:"opening ceremony",meaning:"開会式"},
    {word:"closing ceremony",meaning:"閉会式"},
    {word:"keynote speaker",meaning:"基調講演者"},
    {word:"VIP",meaning:"要人・重要人物"},
    {word:"dress code",meaning:"ドレスコード・服装規定"},
    {word:"formal attire",meaning:"正装・フォーマルウェア"},
    {word:"business casual",meaning:"ビジネスカジュアル"},
    {word:"business card",meaning:"ビジネスカード・名刺"},
    {word:"name card",meaning:"名刺"},
    {word:"handshake",meaning:"握手"},
    {word:"self-introduction",meaning:"自己紹介"},
    {word:"small talk",meaning:"雑談・世間話"},
    {word:"networking opportunity",meaning:"ネットワーキング機会"},
    {word:"post-event follow-up",meaning:"イベント後フォローアップ"},
    {word:"conference call",meaning:"電話会議"},
    {word:"video conference",meaning:"テレビ会議"},
    {word:"Zoom meeting",meaning:"ズームミーティング"},
    {word:"agenda item",meaning:"議事項目"},
    {word:"action item",meaning:"アクションアイテム"},
    {word:"meeting minutes",meaning:"議事録"},
    {word:"wrap-up",meaning:"まとめ・終了"},
    {word:"debrief",meaning:"ブリーフィング後の報告"},
    {word:"recap",meaning:"要点整理・振り返り"},
    {word:"follow-through",meaning:"フォロースルー・実行"},
    {word:"deliverable",meaning:"成果物・納品物"},
    {word:"timeline management",meaning:"タイムライン管理"},
    {word:"on-site",meaning:"現地・オンサイト"},
    {word:"off-site",meaning:"社外・オフサイト"},
    {word:"remote participation",meaning:"リモート参加"},
    {word:"hybrid participation",meaning:"ハイブリッド参加"},
    {word:"event sponsorship",meaning:"イベントスポンサーシップ"},
    {word:"brand activation",meaning:"ブランドアクティベーション"},
    {word:"experiential marketing",meaning:"体験型マーケティング"},
    {word:"agreement",meaning:"合意・協定・契約"},
    {word:"terms and conditions",meaning:"利用規約・条件"},
    {word:"clause",meaning:"条項・節・条文"},
    {word:"addendum",meaning:"追記・付則・追加条項"},
    {word:"exhibit",meaning:"添付書類・証拠物"},
    {word:"appendix",meaning:"付録・添付書類"},
    {word:"schedule document",meaning:"別表・付属書類"},
    {word:"binding",meaning:"拘束力のある・法的効力"},
    {word:"enforceable",meaning:"執行可能な"},
    {word:"void",meaning:"無効・空の"},
    {word:"voidable",meaning:"取消可能な"},
    {word:"breach",meaning:"違反・侵害する"},
    {word:"breach of contract",meaning:"契約違反"},
    {word:"remedy",meaning:"救済措置・解決策"},
    {word:"indemnification",meaning:"補償・損害賠償"},
    {word:"limitation of liability",meaning:"責任制限"},
    {word:"force majeure",meaning:"不可抗力"},
    {word:"jurisdiction",meaning:"管轄権・裁判権"},
    {word:"governing law",meaning:"準拠法・適用法"},
    {word:"dispute resolution",meaning:"紛争解決"},
    {word:"lawsuit",meaning:"訴訟・民事訴訟"},
    {word:"plaintiff",meaning:"原告"},
    {word:"defendant",meaning:"被告"},
    {word:"attorney",meaning:"弁護士・代理人"},
    {word:"legal counsel",meaning:"法律顧問・弁護士"},
    {word:"legal advice",meaning:"法律的アドバイス"},
    {word:"confidentiality agreement",meaning:"秘密保持契約"},
    {word:"non-disclosure agreement",meaning:"秘密保持契約・NDA"}
  ],
  "TOEIC_Day18": [
    {word:"英単語",meaning:"和訳"},
    {word:"global minimum tax",meaning:"グローバル最低税率"},
    {word:"Pillar Two",meaning:"ピラーツー・国際課税ルール"},
    {word:"economic substance",meaning:"経済的実体"},
    {word:"holding company structure",meaning:"持株会社構造"},
    {word:"offshore structure",meaning:"オフショア構造"},
    {word:"tax haven",meaning:"タックスヘイブン"},
    {word:"transparency initiative",meaning:"透明性イニシアチブ"},
    {word:"automatic exchange of information",meaning:"自動的情報交換"},
    {word:"common reporting standard",meaning:"共通報告基準・CRS"},
    {word:"FATCA",meaning:"外国口座税務コンプライアンス法"},
    {word:"accomplish",meaning:"成し遂げる・達成する"},
    {word:"achieve",meaning:"達成する・成功する"},
    {word:"adapt",meaning:"適応する・調整する"},
    {word:"address",meaning:"対処する・取り組む・住所"},
    {word:"advance",meaning:"前進する・改善する・進歩"},
    {word:"advocate",meaning:"支持する・提唱者"},
    {word:"align",meaning:"調整する・一致させる"},
    {word:"allocate",meaning:"割り当てる・配分する"},
    {word:"anticipate",meaning:"予測する・期待する"},
    {word:"articulate",meaning:"明確に述べる・明瞭な"},
    {word:"capitalize",meaning:"資本化する・活用する"},
    {word:"clarify",meaning:"明確にする・説明する"},
    {word:"commence",meaning:"開始する・着手する"},
    {word:"commit",meaning:"約束する・遂行する"},
    {word:"communicate",meaning:"伝える・情報を共有する"},
    {word:"compile",meaning:"まとめる・編集する"},
    {word:"conceptualize",meaning:"概念化する・アイデアを形にする"},
    {word:"consolidate",meaning:"統合する・強固にする"},
    {word:"coordinate",meaning:"調整する・まとめる"},
    {word:"customize",meaning:"カスタマイズする・特注する"},
    {word:"demonstrate",meaning:"示す・説明する"},
    {word:"designate",meaning:"指定する・任命する"},
    {word:"determine",meaning:"決定する・判断する"},
    {word:"develop",meaning:"開発する・発展する"},
    {word:"differentiate",meaning:"区別する・差別化する"},
    {word:"drive",meaning:"推進する・原動力となる"},
    {word:"eliminate",meaning:"除去する・排除する"},
    {word:"empower",meaning:"権限を与える・強化する"},
    {word:"enable",meaning:"可能にする・実現する"},
    {word:"enhance",meaning:"向上させる・強化する"},
    {word:"ensure",meaning:"確保する・保証する"},
    {word:"establish",meaning:"設立する・確立する"},
    {word:"facilitate",meaning:"促進する・容易にする"},
    {word:"finalize",meaning:"最終化する・完成させる"},
    {word:"focus",meaning:"集中する・焦点を当てる"},
    {word:"formulate",meaning:"策定する・立案する"},
    {word:"generate",meaning:"生成する・生み出す"},
    {word:"identify",meaning:"特定する・識別する"},
    {word:"improve",meaning:"改善する・向上させる"},
    {word:"incorporate",meaning:"組み込む・設立する"},
    {word:"increase",meaning:"増加する・増やす"},
    {word:"initiate",meaning:"開始する・着手する"},
    {word:"maintain",meaning:"維持する・保持する"},
    {word:"maximize",meaning:"最大化する・最大限に活用する"},
    {word:"measure",meaning:"測定する・評価する"},
    {word:"minimize",meaning:"最小化する・最小限にする"},
    {word:"mitigate",meaning:"軽減する・緩和する"},
    {word:"monitor",meaning:"監視する・モニタリングする"},
    {word:"motivate",meaning:"動機付ける・励ます"},
    {word:"obtain",meaning:"取得する・入手する"},
    {word:"optimize",meaning:"最適化する"},
    {word:"organize",meaning:"整理する・組織する"},
    {word:"outline",meaning:"概要を述べる・概説する"},
    {word:"oversee",meaning:"監督する・管理する"},
    {word:"perform",meaning:"実行する・遂行する"},
    {word:"plan",meaning:"計画する・立案する"},
    {word:"present",meaning:"提示する・発表する"},
    {word:"prioritize",meaning:"優先順位をつける"},
    {word:"process",meaning:"処理する・プロセス"},
    {word:"propose",meaning:"提案する・申し出る"},
    {word:"reduce",meaning:"削減する・減らす"},
    {word:"resolve",meaning:"解決する・決意する"},
    {word:"simplify",meaning:"簡略化する・単純化する"},
    {word:"specify",meaning:"明記する・指定する"},
    {word:"standardize",meaning:"標準化する"},
    {word:"strengthen",meaning:"強化する・増強する"},
    {word:"streamline",meaning:"合理化する・効率化する"},
    {word:"support",meaning:"支援する・サポートする"},
    {word:"sustain",meaning:"持続する・支える"},
    {word:"track",meaning:"追跡する・記録する"},
    {word:"transform",meaning:"変革する・変換する"},
    {word:"utilize",meaning:"活用する・利用する"},
    {word:"verify",meaning:"確認する・検証する"},
    {word:"accelerate",meaning:"加速する・速める"},
    {word:"benchmark performance",meaning:"業績をベンチマークする"},
    {word:"brainstorm",meaning:"ブレインストーミングする"},
    {word:"calibrate",meaning:"調整する・較正する"},
    {word:"categorize",meaning:"分類する・カテゴリー分けする"},
    {word:"collaborate with",meaning:"〜と協力する"},
    {word:"comply with",meaning:"〜に従う・遵守する"},
    {word:"convene",meaning:"招集する・開催する"},
    {word:"correspond with",meaning:"〜と通信する・対応する"},
    {word:"diagnose",meaning:"診断する・原因を特定する"},
    {word:"document",meaning:"文書化する・記録する"},
    {word:"draft a proposal",meaning:"提案書を作成する"},
    {word:"execute a plan",meaning:"計画を実行する"},
    {word:"gain approval",meaning:"承認を得る"},
    {word:"handle inquiries",meaning:"問い合わせに対応する"},
    {word:"head a project",meaning:"プロジェクトを主導する"},
    {word:"implement changes",meaning:"変更を実施する"}
  ],
  "TOEIC_Day15": [
    {word:"英単語",meaning:"和訳"},
    {word:"pharmacokinetics",meaning:"薬物動態学"},
    {word:"pharmacodynamics",meaning:"薬力学"},
    {word:"dosage",meaning:"用量・投与量"},
    {word:"formulation",meaning:"製剤・配合"},
    {word:"active pharmaceutical ingredient",meaning:"有効医薬品成分・API"},
    {word:"excipient",meaning:"賦形剤"},
    {word:"drug interaction",meaning:"薬物相互作用"},
    {word:"contraindication",meaning:"禁忌"},
    {word:"therapeutic window",meaning:"治療域・治療窓"},
    {word:"bioavailability",meaning:"バイオアベイラビリティ・生物学的利用能"},
    {word:"clinical endpoint",meaning:"臨床エンドポイント"},
    {word:"primary endpoint",meaning:"主要エンドポイント"},
    {word:"secondary endpoint",meaning:"副次エンドポイント"},
    {word:"placebo",meaning:"プラセボ・偽薬"},
    {word:"randomized controlled trial",meaning:"無作為化比較試験・RCT"},
    {word:"double-blind study",meaning:"二重盲検試験"},
    {word:"informed consent",meaning:"インフォームドコンセント・説明と同意"},
    {word:"IRB",meaning:"施設内審査委員会"},
    {word:"ethics committee",meaning:"倫理委員会"},
    {word:"protocol deviation",meaning:"プロトコル逸脱"},
    {word:"serious adverse event",meaning:"重篤有害事象・SAE"},
    {word:"expedited reporting",meaning:"迅速報告"},
    {word:"regulatory intelligence",meaning:"規制情報"},
    {word:"health technology assessment",meaning:"医療技術評価・HTA"},
    {word:"pharmacoeconomics",meaning:"薬剤経済学"},
    {word:"cost-effectiveness",meaning:"費用対効果"},
    {word:"quality-adjusted life year",meaning:"質調整生存年・QALY"},
    {word:"reimbursement strategy",meaning:"償還戦略"},
    {word:"market access",meaning:"マーケットアクセス"},
    {word:"payer",meaning:"支払者・医療保険者"},
    {word:"formulary",meaning:"医薬品リスト・処方集"},
    {word:"managed care",meaning:"マネージドケア"},
    {word:"outcomes research",meaning:"アウトカム研究"},
    {word:"real-world evidence",meaning:"リアルワールドエビデンス・RWE"},
    {word:"electronic health record",meaning:"電子健康記録・EHR"},
    {word:"telemedicine",meaning:"遠隔医療・テレメディスン"},
    {word:"digital health",meaning:"デジタルヘルス"},
    {word:"health informatics",meaning:"医療情報学"},
    {word:"curriculum",meaning:"カリキュラム・教育課程"},
    {word:"syllabus",meaning:"シラバス・授業計画"},
    {word:"learning objective",meaning:"学習目標"},
    {word:"competency",meaning:"コンピテンシー・能力"},
    {word:"continuing education",meaning:"継続教育・生涯学習"},
    {word:"professional development",meaning:"プロフェッショナル開発"},
    {word:"e-learning",meaning:"eラーニング・オンライン学習"},
    {word:"blended learning",meaning:"ブレンデッドラーニング・混合学習"},
    {word:"microlearning",meaning:"マイクロラーニング・短時間学習"},
    {word:"gamification",meaning:"ゲーミフィケーション"},
    {word:"simulation training",meaning:"シミュレーション訓練"},
    {word:"role-playing",meaning:"ロールプレイ・役割演技"},
    {word:"on-the-job training",meaning:"OJT・職場内訓練"},
    {word:"classroom training",meaning:"集合研修・座学"},
    {word:"knowledge transfer",meaning:"知識移転・ノウハウ伝承"},
    {word:"skills gap",meaning:"スキルギャップ・能力不足"},
    {word:"talent development",meaning:"タレント開発・人材育成"},
    {word:"executive education",meaning:"経営幹部教育"},
    {word:"MBA",meaning:"経営学修士"},
    {word:"corporate university",meaning:"企業大学"},
    {word:"learning management system",meaning:"学習管理システム・LMS"},
    {word:"course completion",meaning:"コース修了"},
    {word:"certificate of completion",meaning:"修了証"},
    {word:"digital badge",meaning:"デジタルバッジ・デジタル証明"},
    {word:"continuing professional development",meaning:"継続的専門能力開発・CPD"},
    {word:"professional association",meaning:"専門職団体"},
    {word:"industry certification",meaning:"業界認定資格"},
    {word:"license renewal",meaning:"ライセンス更新"},
    {word:"training needs analysis",meaning:"研修ニーズ分析"},
    {word:"instructional design",meaning:"教授設計"},
    {word:"content development",meaning:"コンテンツ開発・教材作成"},
    {word:"ADDIE model",meaning:"ADDIEモデル・教育設計手法"},
    {word:"Kirkpatrick model",meaning:"カークパトリックモデル・研修評価"},
    {word:"ROI of training",meaning:"研修の投資収益率"},
    {word:"engagement metrics",meaning:"エンゲージメント指標"},
    {word:"knowledge retention",meaning:"知識定着・記憶保持"},
    {word:"transfer of learning",meaning:"学習転移"},
    {word:"spaced repetition",meaning:"間隔反復法"},
    {word:"retrieval practice",meaning:"検索練習・想起練習"},
    {word:"feedback loop",meaning:"フィードバックループ"},
    {word:"formative assessment",meaning:"形成的評価"},
    {word:"summative assessment",meaning:"総括的評価"},
    {word:"performance support",meaning:"パフォーマンスサポート"},
    {word:"job aid",meaning:"職務支援ツール"},
    {word:"quick reference guide",meaning:"クイックリファレンスガイド"},
    {word:"knowledge management",meaning:"ナレッジマネジメント"},
    {word:"communities of practice",meaning:"実践コミュニティ"},
    {word:"peer learning",meaning:"ピア学習・同僚間学習"},
    {word:"collaborative learning",meaning:"協調学習"},
    {word:"social learning",meaning:"ソーシャルラーニング"},
    {word:"personalized learning",meaning:"個別化学習"},
    {word:"adaptive learning",meaning:"アダプティブラーニング"},
    {word:"cross-functional training",meaning:"クロスファンクショナル研修"},
    {word:"shadow program",meaning:"シャドウプログラム・見学研修"},
    {word:"stretch assignment",meaning:"ストレッチアサインメント"},
    {word:"readiness assessment",meaning:"準備度評価"},
    {word:"academic credential",meaning:"学術的資格"},
    {word:"prior learning assessment",meaning:"事前学習評価"},
    {word:"competency mapping",meaning:"コンピテンシーマッピング"},
    {word:"skill inventory",meaning:"スキルインベントリー"},
    {word:"learning path",meaning:"ラーニングパス・学習経路"},
    {word:"curriculum development",meaning:"カリキュラム開発"}
  ],
  "TOEIC_Day13": [
    {word:"英単語",meaning:"和訳"},
    {word:"proactive service",meaning:"プロアクティブサービス"},
    {word:"customer journey map",meaning:"カスタマージャーニーマップ"},
    {word:"touchpoint",meaning:"タッチポイント・接点"},
    {word:"pain point",meaning:"ペインポイント・課題"},
    {word:"customer experience",meaning:"顧客体験・CX"},
    {word:"voice of customer",meaning:"顧客の声・VOC"},
    {word:"empathy",meaning:"共感・思いやり"},
    {word:"active listening",meaning:"アクティブリスニング・傾聴"},
    {word:"problem solving",meaning:"問題解決"},
    {word:"de-escalation",meaning:"緊張緩和・沈静化"},
    {word:"conflict resolution",meaning:"紛争解決・対立解消"},
    {word:"apology",meaning:"謝罪"},
    {word:"service recovery",meaning:"サービスリカバリー"},
    {word:"continuous improvement",meaning:"継続的改善"},
    {word:"process improvement",meaning:"プロセス改善"},
    {word:"standard operating procedure",meaning:"標準作業手順書・SOP"},
    {word:"best practice",meaning:"ベストプラクティス"},
    {word:"benchmarking",meaning:"ベンチマーキング"},
    {word:"case study",meaning:"事例研究・ケーススタディ"},
    {word:"satisfaction survey",meaning:"満足度調査"},
    {word:"Net Promoter Score",meaning:"NPS・顧客推奨度"},
    {word:"service level",meaning:"サービスレベル"},
    {word:"response rate",meaning:"回答率・応答率"},
    {word:"resolution rate",meaning:"解決率"},
    {word:"escalation rate",meaning:"エスカレーション率"},
    {word:"handle time",meaning:"処理時間・対応時間"},
    {word:"average handle time",meaning:"平均処理時間・AHT"},
    {word:"queue management",meaning:"キュー管理・待ち行列管理"},
    {word:"workforce management",meaning:"要員管理・WFM"},
    {word:"shift scheduling",meaning:"シフト管理・スケジューリング"},
    {word:"service desk",meaning:"サービスデスク"},
    {word:"incident management",meaning:"インシデント管理"},
    {word:"problem management",meaning:"問題管理"},
    {word:"change request",meaning:"変更依頼"},
    {word:"ITIL",meaning:"ITサービス管理のベストプラクティス"},
    {word:"service catalog",meaning:"サービスカタログ"},
    {word:"service request",meaning:"サービスリクエスト"},
    {word:"knowledge article",meaning:"ナレッジ記事"},
    {word:"self-help",meaning:"セルフヘルプ・自己解決"},
    {word:"automation workflow",meaning:"自動化ワークフロー"},
    {word:"chatbot integration",meaning:"チャットボット統合"},
    {word:"AI-powered support",meaning:"AI活用サポート"},
    {word:"sentiment analysis",meaning:"感情分析・センチメント分析"},
    {word:"text analytics",meaning:"テキスト分析"},
    {word:"speech analytics",meaning:"音声分析"},
    {word:"customer health score",meaning:"顧客ヘルススコア"},
    {word:"account management",meaning:"アカウント管理"},
    {word:"success manager",meaning:"カスタマーサクセスマネージャー"},
    {word:"onboarding support",meaning:"オンボーディングサポート"},
    {word:"product adoption",meaning:"製品採用・活用"},
    {word:"renewal management",meaning:"更新管理"},
    {word:"expansion revenue",meaning:"拡張収益・アップセル収益"},
    {word:"net revenue retention",meaning:"純収益維持率・NRR"},
    {word:"gross revenue retention",meaning:"総収益維持率・GRR"},
    {word:"manufacturing",meaning:"製造・生産・メーカー"},
    {word:"production",meaning:"生産・製造・産出"},
    {word:"assembly",meaning:"組み立て・アセンブリ"},
    {word:"fabrication",meaning:"製作・加工・組立"},
    {word:"machining",meaning:"機械加工"},
    {word:"welding",meaning:"溶接"},
    {word:"casting",meaning:"鋳造・鋳型"},
    {word:"forging",meaning:"鍛造"},
    {word:"injection molding",meaning:"射出成形"},
    {word:"stamping",meaning:"プレス加工"},
    {word:"CNC machining",meaning:"CNC加工"},
    {word:"3D printing",meaning:"3Dプリンティング・積層造形"},
    {word:"robotics",meaning:"ロボティクス・ロボット工学"},
    {word:"sampling",meaning:"サンプリング・抜き取り検査"},
    {word:"statistical process control",meaning:"統計的プロセス管理・SPC"},
    {word:"total quality management",meaning:"全社的品質管理・TQM"},
    {word:"ISO certification",meaning:"ISO認証"},
    {word:"5S methodology",meaning:"5S手法"},
    {word:"overall equipment effectiveness",meaning:"設備総合効率・OEE"},
    {word:"capacity planning",meaning:"生産能力計画"},
    {word:"production schedule",meaning:"生産スケジュール"},
    {word:"work order",meaning:"作業指示書"},
    {word:"bill of materials",meaning:"部品表・BOM"},
    {word:"material requirements planning",meaning:"資材所要量計画・MRP"},
    {word:"raw material",meaning:"原材料・原料"},
    {word:"work in progress",meaning:"仕掛品・WIP"},
    {word:"finished goods",meaning:"完成品"},
    {word:"cycle time",meaning:"サイクルタイム"},
    {word:"takt time",meaning:"タクトタイム"},
    {word:"batch production",meaning:"バッチ生産"},
    {word:"continuous production",meaning:"連続生産"},
    {word:"mass production",meaning:"大量生産"},
    {word:"custom production",meaning:"受注生産"},
    {word:"pilot run",meaning:"試験生産・パイロットラン"},
    {word:"ramp-up",meaning:"立ち上げ・生産増加"},
    {word:"scale-up",meaning:"スケールアップ・拡大"},
    {word:"contract manufacturing",meaning:"委託製造"},
    {word:"OEM",meaning:"相手先ブランド製造"},
    {word:"ODM",meaning:"自社設計製造"},
    {word:"value engineering",meaning:"バリューエンジニアリング"},
    {word:"design for manufacturing",meaning:"製造性設計・DFM"},
    {word:"concurrent engineering",meaning:"コンカレントエンジニアリング"},
    {word:"product lifecycle management",meaning:"製品ライフサイクル管理・PLM"},
    {word:"computer-aided design",meaning:"CAD・コンピュータ支援設計"},
    {word:"computer-aided manufacturing",meaning:"CAM・コンピュータ支援製造"},
    {word:"simulation",meaning:"シミュレーション"}
  ],
  "TOEIC_Day20": [
    {word:"英単語",meaning:"和訳"},
    {word:"macroeconomic indicator",meaning:"マクロ経済指標"},
    {word:"leading indicator",meaning:"先行指標"},
    {word:"lagging indicator",meaning:"遅行指標"},
    {word:"coincident indicator",meaning:"一致指標"},
    {word:"business cycle",meaning:"景気循環・ビジネスサイクル"},
    {word:"contingency reserve",meaning:"コンティンジェンシー準備金・予備費"},
    {word:"goodwill",meaning:"のれん・営業権"},
    {word:"intangible asset",meaning:"無形資産"},
    {word:"tangible asset",meaning:"有形資産"},
    {word:"net asset value",meaning:"純資産価値・NAV"},
    {word:"equity financing",meaning:"エクイティファイナンス・株式調達"},
    {word:"debt financing",meaning:"デットファイナンス・負債調達"},
    {word:"convertible note",meaning:"転換社債・コンバーティブルノート"},
    {word:"pre-money valuation",meaning:"プレマネーバリュエーション"},
    {word:"post-money valuation",meaning:"ポストマネーバリュエーション"},
    {word:"runway",meaning:"ランウェイ・資金枯渇までの期間"},
    {word:"burn rate",meaning:"バーンレート・資金消費速度"},
    {word:"unit economics",meaning:"ユニットエコノミクス"},
    {word:"fixed cost",meaning:"固定費"},
    {word:"variable cost",meaning:"変動費"},
    {word:"marginal cost",meaning:"限界費用"},
    {word:"sunk cost",meaning:"サンクコスト・埋没費用"},
    {word:"opportunity cost",meaning:"機会費用"},
    {word:"cost of capital",meaning:"資本コスト"},
    {word:"weighted average cost of capital",meaning:"加重平均資本コスト・WACC"},
    {word:"hurdle rate",meaning:"ハードルレート・最低収益率"},
    {word:"net present value",meaning:"正味現在価値・NPV"},
    {word:"internal rate of return",meaning:"内部収益率・IRR"},
    {word:"payback period",meaning:"回収期間"},
    {word:"discounted cash flow",meaning:"割引キャッシュフロー・DCF"},
    {word:"terminal value",meaning:"ターミナルバリュー・残存価値"},
    {word:"synergy",meaning:"シナジー・相乗効果"},
    {word:"integration plan",meaning:"統合計画・PMI"},
    {word:"divestiture",meaning:"事業売却・ダイベスティチャー"},
    {word:"carve-out",meaning:"カーブアウト・事業分離"},
    {word:"management fee",meaning:"管理手数料"},
    {word:"carried interest",meaning:"キャリードインタレスト・成功報酬"},
    {word:"limited partner",meaning:"リミテッドパートナー・LP"},
    {word:"general partner",meaning:"ジェネラルパートナー・GP"},
    {word:"hostile takeover",meaning:"敵対的買収"},
    {word:"white knight",meaning:"ホワイトナイト・友好的買収者"},
    {word:"poison pill",meaning:"ポイズンピル・買収防衛策"},
    {word:"golden parachute",meaning:"ゴールデンパラシュート"},
    {word:"shareholder activism",meaning:"株主アクティビズム"},
    {word:"proxy voting",meaning:"代理投票"},
    {word:"say on pay",meaning:"役員報酬の株主投票"},
    {word:"executive compensation",meaning:"役員報酬"},
    {word:"stock option",meaning:"ストックオプション"},
    {word:"restricted stock unit",meaning:"制限付き株式ユニット・RSU"},
    {word:"employee stock ownership plan",meaning:"従業員持株制度・ESOP"},
    {word:"deferred compensation",meaning:"繰延報酬"},
    {word:"clawback",meaning:"クローバック・報酬返還請求"},
    {word:"long-term incentive plan",meaning:"長期インセンティブ計画・LTIP"},
    {word:"total rewards",meaning:"トータルリワード・総報酬"},
    {word:"job evaluation",meaning:"職務評価"},
    {word:"pay equity analysis",meaning:"賃金格差分析"},
    {word:"salary band",meaning:"給与レンジ・給与帯"},
    {word:"market pricing",meaning:"マーケットプライシング・市場賃金調査"},
    {word:"merit increase",meaning:"業績連動昇給"},
    {word:"cost of living adjustment",meaning:"生活費調整・COLA"},
    {word:"pay transparency",meaning:"賃金透明性"},
    {word:"gender pay gap",meaning:"男女賃金格差"},
    {word:"minimum wage",meaning:"最低賃金"},
    {word:"living wage",meaning:"生活賃金"},
    {word:"labor market",meaning:"労働市場"},
    {word:"talent acquisition",meaning:"人材獲得"},
    {word:"employer brand",meaning:"雇用主ブランディング"},
    {word:"employee value proposition",meaning:"従業員への価値提案・EVP"},
    {word:"candidate experience",meaning:"候補者体験"},
    {word:"operating lease",meaning:"オペレーティングリース"},
    {word:"finance lease",meaning:"ファイナンスリース"},
    {word:"contribution margin",meaning:"貢献利益率"},
    {word:"gross margin",meaning:"グロスマージン・粗利率"},
    {word:"comparable company analysis",meaning:"比較会社分析"},
    {word:"post-merger integration",meaning:"統合後整合"},
    {word:"activist investor",meaning:"アクティビスト投資家"},
    {word:"phantom stock",meaning:"ファントムストック"},
    {word:"SAFE note",meaning:"SAFE・将来株式取得権"},
    {word:"distressed investing",meaning:"ディストレスト投資"},
    {word:"secondary investment",meaning:"セカンダリー投資"},
    {word:"co-investment",meaning:"共同投資"},
    {word:"fund of funds",meaning:"ファンドオブファンズ"},
    {word:"staggered board",meaning:"段階的取締役会"},
    {word:"proxy fight",meaning:"プロキシーファイト・委任状争奪戦"},
    {word:"pay compression",meaning:"賃金圧縮"},
    {word:"performance unit",meaning:"パフォーマンスユニット"},
    {word:"short-term incentive plan",meaning:"短期インセンティブ計画・STIP"},
    {word:"vendor management",meaning:"ベンダー管理"},
    {word:"category management",meaning:"カテゴリー管理"},
    {word:"spend analysis",meaning:"支出分析"},
    {word:"total cost of ownership",meaning:"総所有コスト・TCO"},
    {word:"supplier relationship management",meaning:"サプライヤー関係管理・SRM"},
    {word:"demand forecasting",meaning:"需要予測"},
    {word:"capacity utilization",meaning:"設備利用率"},
    {word:"production efficiency",meaning:"生産効率"},
    {word:"first pass yield",meaning:"初回合格率・FPY"},
    {word:"scrap rate",meaning:"スクラップ率・廃棄率"},
    {word:"rework",meaning:"手直し・再作業"},
    {word:"yield rate",meaning:"歩留まり率"},
    {word:"ergonomic assessment",meaning:"人間工学的評価"}
  ],
  "TOEIC_Day19": [
    {word:"英単語",meaning:"和訳"},
    {word:"issue a report",meaning:"報告書を発行する"},
    {word:"manage a team",meaning:"チームを管理する"},
    {word:"negotiate terms",meaning:"条件を交渉する"},
    {word:"outline expectations",meaning:"期待事項を概説する"},
    {word:"pitch an idea",meaning:"アイデアを売り込む"},
    {word:"present findings",meaning:"調査結果を発表する"},
    {word:"pursue opportunities",meaning:"機会を追求する"},
    {word:"review progress",meaning:"進捗を確認する"},
    {word:"scale operations",meaning:"事業を拡大する"},
    {word:"set objectives",meaning:"目標を設定する"},
    {word:"share insights",meaning:"知見を共有する"},
    {word:"paradigm shift",meaning:"パラダイムシフト・考え方の転換"},
    {word:"disruptive innovation",meaning:"破壊的イノベーション"},
    {word:"blue ocean strategy",meaning:"ブルーオーシャン戦略"},
    {word:"red ocean strategy",meaning:"レッドオーシャン戦略"},
    {word:"design thinking",meaning:"デザイン思考"},
    {word:"systems thinking",meaning:"システム思考"},
    {word:"lean startup",meaning:"リーンスタートアップ"},
    {word:"product-market validation",meaning:"プロダクト市場適合性検証"},
    {word:"decacorn",meaning:"デカコーン・評価額100億ドル超"},
    {word:"exit strategy",meaning:"イグジット戦略"},
    {word:"acqui-hire",meaning:"アクワイハイア・人材目的の買収"},
    {word:"valuation",meaning:"企業価値評価・バリュエーション"},
    {word:"cap table",meaning:"資本構成表"},
    {word:"seed funding",meaning:"シード資金・初期資金調達"},
    {word:"series A funding",meaning:"シリーズA資金調達"},
    {word:"angel investor",meaning:"エンジェル投資家"},
    {word:"crowdfunding",meaning:"クラウドファンディング"},
    {word:"tokenization",meaning:"トークン化"},
    {word:"decentralized finance",meaning:"分散型金融・DeFi"},
    {word:"non-fungible token",meaning:"非代替性トークン・NFT"},
    {word:"Web3",meaning:"ウェブスリー・分散型インターネット"},
    {word:"metaverse",meaning:"メタバース・仮想空間"},
    {word:"augmented reality",meaning:"拡張現実・AR"},
    {word:"virtual reality",meaning:"仮想現実・VR"},
    {word:"mixed reality",meaning:"複合現実・MR"},
    {word:"autonomous vehicle",meaning:"自動運転車"},
    {word:"smart city",meaning:"スマートシティ"},
    {word:"smart grid",meaning:"スマートグリッド"},
    {word:"precision medicine",meaning:"精密医療"},
    {word:"genomics",meaning:"ゲノミクス・ゲノム科学"},
    {word:"biotechnology",meaning:"バイオテクノロジー・生命工学"},
    {word:"nanotechnology",meaning:"ナノテクノロジー"},
    {word:"quantum computing",meaning:"量子コンピューティング"},
    {word:"geopolitical risk",meaning:"地政学的リスク"},
    {word:"deglobalization",meaning:"脱グローバリゼーション"},
    {word:"reshoring",meaning:"リショアリング・生産の国内回帰"},
    {word:"friend-shoring",meaning:"フレンドショアリング・同盟国への移転"},
    {word:"strategic autonomy",meaning:"戦略的自律性"},
    {word:"economic security",meaning:"経済安全保障"},
    {word:"resilience",meaning:"レジリエンス・回復力"},
    {word:"antifragility",meaning:"反脆弱性"},
    {word:"scenario planning",meaning:"シナリオプランニング"},
    {word:"strategic foresight",meaning:"戦略的先見性"},
    {word:"megatrend",meaning:"メガトレンド・巨大トレンド"},
    {word:"VUCA",meaning:"不安定・不確実・複雑・曖昧"},
    {word:"black swan event",meaning:"ブラックスワン・想定外大事件"},
    {word:"grey rhino",meaning:"グレーリノ・予測可能な大リスク"},
    {word:"spin-off",meaning:"スピンオフ・分社化"},
    {word:"merger and acquisition",meaning:"合併・買収・M&A"},
    {word:"leveraged buyout",meaning:"レバレッジド・バイアウト・LBO"},
    {word:"management buyout",meaning:"マネジメント・バイアウト・MBO"},
    {word:"SPAC",meaning:"特別目的買収会社"},
    {word:"secondary market",meaning:"セカンダリーマーケット・流通市場"},
    {word:"private placement memo",meaning:"私募メモランダム"},
    {word:"roadshow",meaning:"ロードショー・投資家説明会"},
    {word:"book building",meaning:"ブックビルディング・需要積み上げ"},
    {word:"lock-up period",meaning:"ロックアップ期間"},
    {word:"dilution",meaning:"希薄化・ダイリューション"},
    {word:"anti-dilution clause",meaning:"希薄化防止条項"},
    {word:"liquidation preference",meaning:"清算優先権"},
    {word:"drag-along right",meaning:"ドラッグアロング権"},
    {word:"tag-along right",meaning:"タグアロング権"},
    {word:"right of first refusal",meaning:"先買権"},
    {word:"vesting schedule",meaning:"権利確定スケジュール"},
    {word:"cliff vesting",meaning:"クリフベスティング"},
    {word:"earnout",meaning:"アーンアウト・業績連動支払い"},
    {word:"ratchet",meaning:"ラチェット・価格調整条項"},
    {word:"down round",meaning:"ダウンラウンド・評価額引き下げ調達"},
    {word:"bridge financing",meaning:"ブリッジファイナンス"},
    {word:"mezzanine financing",meaning:"メザニンファイナンス"},
    {word:"subordinated debt",meaning:"劣後債務"},
    {word:"super senior debt",meaning:"スーパーシニア債務"},
    {word:"covenant-lite",meaning:"コベナント・ライト"},
    {word:"payment in kind",meaning:"現物払い・PIK"},
    {word:"total return swap",meaning:"トータルリターンスワップ"},
    {word:"credit default swap",meaning:"クレジットデフォルトスワップ・CDS"},
    {word:"collateralized debt obligation",meaning:"債務担保証券・CDO"},
    {word:"asset-backed security",meaning:"資産担保証券・ABS"},
    {word:"mortgage-backed security",meaning:"住宅ローン担保証券・MBS"},
    {word:"shadow banking",meaning:"シャドーバンキング"},
    {word:"special purpose vehicle",meaning:"特別目的ビークル・SPV"},
    {word:"off-balance sheet",meaning:"オフバランス・貸借対照表外"},
    {word:"securitization",meaning:"証券化"},
    {word:"repurchase agreement",meaning:"レポ取引・買戻し合意"},
    {word:"prime brokerage",meaning:"プライムブローカレッジ"},
    {word:"dark pool",meaning:"ダークプール・非公開取引"},
    {word:"market microstructure",meaning:"市場マイクロストラクチャー"},
    {word:"regulatory arbitrage",meaning:"規制裁定"},
    {word:"systemic importance",meaning:"システム上の重要性"}
  ],
  "TOEIC_Day16": [
    {word:"英単語",meaning:"和訳"},
    {word:"subject matter expert",meaning:"領域専門家・SME"},
    {word:"facilitator",meaning:"ファシリテーター・進行役"},
    {word:"trainer",meaning:"トレーナー・講師"},
    {word:"trainee",meaning:"研修生・受講者"},
    {word:"participant",meaning:"参加者・受講者"},
    {word:"cohort",meaning:"コホート・同期グループ"},
    {word:"learning cohort",meaning:"学習コホート"},
    {word:"boot camp",meaning:"ブートキャンプ・集中研修"},
    {word:"hackathon event",meaning:"ハッカソンイベント"},
    {word:"innovation challenge",meaning:"イノベーションチャレンジ"},
    {word:"certification exam",meaning:"資格試験"},
    {word:"passing score",meaning:"合格点"},
    {word:"retake policy",meaning:"再受験ポリシー"},
    {word:"proctored exam",meaning:"監督付き試験"},
    {word:"online proctoring",meaning:"オンライン監督"},
    {word:"accredited program",meaning:"認定プログラム"},
    {word:"accreditation body",meaning:"認定機関"},
    {word:"quality assurance education",meaning:"教育品質保証"},
    {word:"learning outcome",meaning:"学習成果"},
    {word:"graduate",meaning:"卒業生・卒業する"},
    {word:"alumni",meaning:"卒業生・同窓会"},
    {word:"continuing education unit",meaning:"継続教育単位・CEU"},
    {word:"credit hour",meaning:"単位時間"},
    {word:"transcript",meaning:"成績証明書"},
    {word:"diploma",meaning:"ディプロマ・卒業証書"},
    {word:"degree program",meaning:"学位プログラム"},
    {word:"executive program",meaning:"エグゼクティブプログラム"},
    {word:"certificate program",meaning:"証明書プログラム"},
    {word:"micro-credential",meaning:"マイクロクレデンシャル"},
    {word:"stackable credential",meaning:"積み上げ資格"},
    {word:"open badge",meaning:"オープンバッジ"},
    {word:"digital portfolio",meaning:"デジタルポートフォリオ"},
    {word:"corporate social responsibility",meaning:"企業の社会的責任・CSR"},
    {word:"ESG investing",meaning:"ESG投資"},
    {word:"carbon footprint reduction",meaning:"カーボンフットプリント削減"},
    {word:"net zero commitment",meaning:"ネットゼロコミットメント"},
    {word:"greenhouse gas emissions",meaning:"温室効果ガス排出量"},
    {word:"carbon dioxide emissions",meaning:"二酸化炭素排出量"},
    {word:"methane reduction",meaning:"メタン削減"},
    {word:"Scope 1 emissions",meaning:"スコープ1排出量・直接排出"},
    {word:"Scope 2 emissions",meaning:"スコープ2排出量・間接排出"},
    {word:"Scope 3 emissions",meaning:"スコープ3排出量"},
    {word:"carbon offset",meaning:"カーボンオフセット"},
    {word:"carbon credit",meaning:"カーボンクレジット"},
    {word:"emissions trading",meaning:"排出権取引"},
    {word:"solar energy",meaning:"太陽エネルギー"},
    {word:"wind energy",meaning:"風力エネルギー"},
    {word:"hydroelectric power",meaning:"水力発電"},
    {word:"biomass energy",meaning:"バイオマスエネルギー"},
    {word:"geothermal energy",meaning:"地熱エネルギー"},
    {word:"energy conservation",meaning:"省エネ・エネルギー保全"},
    {word:"circular economy",meaning:"循環経済"},
    {word:"waste reduction",meaning:"廃棄物削減"},
    {word:"upcycling",meaning:"アップサイクリング"},
    {word:"biodegradable",meaning:"生分解性の"},
    {word:"compostable",meaning:"堆肥化可能な"},
    {word:"responsible sourcing",meaning:"責任ある調達"},
    {word:"fair trade",meaning:"フェアトレード"},
    {word:"ethical supply chain",meaning:"倫理的サプライチェーン"},
    {word:"human rights due diligence",meaning:"人権デューデリジェンス"},
    {word:"biodiversity",meaning:"生物多様性"},
    {word:"ecosystem services",meaning:"生態系サービス"},
    {word:"deforestation",meaning:"森林破壊"},
    {word:"reforestation",meaning:"再植林"},
    {word:"water conservation",meaning:"水資源保全"},
    {word:"water footprint",meaning:"ウォーターフットプリント"},
    {word:"sustainable agriculture",meaning:"持続可能な農業"},
    {word:"organic farming",meaning:"有機農業"},
    {word:"food waste reduction",meaning:"食品廃棄削減"},
    {word:"sustainable packaging",meaning:"サステナブルパッケージング"},
    {word:"plastic reduction",meaning:"プラスチック削減"},
    {word:"ocean pollution",meaning:"海洋汚染"},
    {word:"air quality improvement",meaning:"大気質改善"},
    {word:"pollution control",meaning:"公害防止・汚染管理"},
    {word:"environmental impact assessment",meaning:"環境影響評価"},
    {word:"sustainability report",meaning:"サステナビリティレポート"},
    {word:"GRI standards",meaning:"GRI基準"},
    {word:"TCFD",meaning:"気候関連財務情報開示タスクフォース"},
    {word:"Paris Agreement",meaning:"パリ協定"},
    {word:"COP conference",meaning:"気候変動会議"},
    {word:"Kyoto Protocol",meaning:"京都議定書"},
    {word:"carbon tax",meaning:"炭素税"},
    {word:"cap and trade",meaning:"排出量取引制度"},
    {word:"feed-in tariff",meaning:"固定価格買取制度"},
    {word:"green bond",meaning:"グリーンボンド"},
    {word:"sustainability-linked loan",meaning:"サステナビリティリンクローン"},
    {word:"impact investing",meaning:"インパクト投資"},
    {word:"socially responsible investing",meaning:"社会的責任投資・SRI"},
    {word:"climate risk disclosure",meaning:"気候変動リスク開示"},
    {word:"physical climate risk",meaning:"物理的気候リスク"},
    {word:"transition risk climate",meaning:"移行気候リスク"},
    {word:"stranded asset",meaning:"座礁資産"},
    {word:"just transition",meaning:"公正な移行"},
    {word:"stakeholder engagement",meaning:"ステークホルダーエンゲージメント"},
    {word:"materiality assessment",meaning:"重要性評価"},
    {word:"double materiality",meaning:"ダブルマテリアリティ"},
    {word:"integrated reporting",meaning:"統合報告"},
    {word:"lifecycle assessment",meaning:"ライフサイクル評価・LCA"},
    {word:"product stewardship",meaning:"製品スチュワードシップ"},
    {word:"extended producer responsibility",meaning:"拡大生産者責任・EPR"}
  ],
  "TOEIC_Day07": [
    {word:"英単語",meaning:"和訳"},
    {word:"trade agreement",meaning:"貿易協定"},
    {word:"certificate of origin",meaning:"原産地証明書"},
    {word:"inspection",meaning:"検査・点検・検品"},
    {word:"quality control",meaning:"品質管理・QC"},
    {word:"quality assurance",meaning:"品質保証・QA"},
    {word:"defect",meaning:"欠陥・欠点・不良品"},
    {word:"recall",meaning:"リコール・回収する"},
    {word:"return",meaning:"返品・返却・返戻"},
    {word:"refund",meaning:"返金・払い戻し"},
    {word:"replacement",meaning:"交換・代替品"},
    {word:"lead time",meaning:"リードタイム・納期"},
    {word:"turnaround",meaning:"ターンアラウンド・処理時間"},
    {word:"expedite",meaning:"急送する・早める"},
    {word:"backorder",meaning:"バックオーダー・入荷待ち"},
    {word:"out of stock",meaning:"在庫切れ・品切れ"},
    {word:"reorder",meaning:"再注文・補充注文"},
    {word:"minimum order quantity",meaning:"最小注文数量・MOQ"},
    {word:"bulk order",meaning:"まとめ買い・大量注文"},
    {word:"pallet",meaning:"パレット・荷台"},
    {word:"container",meaning:"コンテナ・容器"},
    {word:"distribution center",meaning:"流通センター・物流センター"},
    {word:"fulfillment center",meaning:"フルフィルメントセンター"},
    {word:"cross-docking",meaning:"クロスドッキング・直送"},
    {word:"last-mile delivery",meaning:"ラストマイル配送"},
    {word:"tracking",meaning:"追跡・トラッキング"},
    {word:"barcode",meaning:"バーコード"},
    {word:"RFID",meaning:"無線周波数識別"},
    {word:"inventory management",meaning:"在庫管理"},
    {word:"SKU",meaning:"最小管理単位"},
    {word:"safety stock",meaning:"安全在庫・バッファー在庫"},
    {word:"cycle counting",meaning:"循環棚卸"},
    {word:"physical inventory",meaning:"現物棚卸"},
    {word:"obsolete",meaning:"陳腐化した・旧式の"},
    {word:"shrinkage",meaning:"在庫減少・ロス・縮小"},
    {word:"waste",meaning:"廃棄・浪費・無駄"},
    {word:"recycling",meaning:"リサイクル・再利用"},
    {word:"reverse logistics",meaning:"逆物流・返品物流"},
    {word:"third-party logistics",meaning:"3PL・サードパーティー物流"},
    {word:"freight forwarder",meaning:"フォワーダー・利用運送業者"},
    {word:"customs broker",meaning:"通関業者"},
    {word:"shipping agent",meaning:"船積み代理店"},
    {word:"carrier",meaning:"運送業者・キャリア"},
    {word:"shipper",meaning:"荷送人・出荷者"},
    {word:"consignee",meaning:"荷受人・受取人"},
    {word:"incoterms",meaning:"インコタームズ・貿易取引条件"},
    {word:"FOB",meaning:"本船渡し条件"},
    {word:"CIF",meaning:"運賃保険料込み条件"},
    {word:"EXW",meaning:"工場渡し条件"},
    {word:"DDP",meaning:"関税込み渡し"},
    {word:"port of entry",meaning:"入港地・入国港"},
    {word:"bonded warehouse",meaning:"保税倉庫"},
    {word:"duty-free",meaning:"免税・関税免除"},
    {word:"trade deficit",meaning:"貿易赤字"},
    {word:"trade surplus",meaning:"貿易黒字"},
    {word:"balance of payments",meaning:"国際収支"},
    {word:"documentary collection",meaning:"荷為替取立"},
    {word:"bank guarantee",meaning:"銀行保証"},
    {word:"insurance certificate",meaning:"保険証明書"},
    {word:"packing list",meaning:"梱包明細書"},
    {word:"commercial invoice",meaning:"商業送り状"},
    {word:"airway bill",meaning:"航空貨物運送状"},
    {word:"remittance",meaning:"送金・海外送金"},
    {word:"correspondent bank",meaning:"コルレス銀行"},
    {word:"SWIFT",meaning:"国際銀行間通信協会"},
    {word:"international payment",meaning:"国際決済"},
    {word:"exchange rate",meaning:"為替レート"},
    {word:"spot rate",meaning:"直物レート"},
    {word:"forward rate",meaning:"先物レート"},
    {word:"currency risk",meaning:"為替リスク"},
    {word:"currency swap",meaning:"通貨スワップ"},
    {word:"forward contract",meaning:"先物契約"},
    {word:"purchasing power parity",meaning:"購買力平価・PPP"},
    {word:"green logistics",meaning:"グリーン物流"},
    {word:"carbon footprint",meaning:"カーボンフットプリント"},
    {word:"cold chain",meaning:"コールドチェーン・低温物流"},
    {word:"temperature monitoring",meaning:"温度管理"},
    {word:"shelf life",meaning:"賞味期限・有効期限"},
    {word:"expiry date",meaning:"有効期限・使用期限"},
    {word:"traceability",meaning:"トレーサビリティ・追跡可能性"},
    {word:"serialization",meaning:"シリアル化・一意番号付与"},
    {word:"supply chain resilience",meaning:"サプライチェーン強靭化"},
    {word:"supply chain diversification",meaning:"サプライチェーンの多様化"},
    {word:"supply chain management",meaning:"サプライチェーン管理"},
    {word:"real estate",meaning:"不動産"},
    {word:"property",meaning:"不動産・財産・物件"},
    {word:"commercial property",meaning:"商業用不動産"},
    {word:"residential property",meaning:"住宅用不動産"},
    {word:"office space",meaning:"オフィス・事務所スペース"},
    {word:"retail space",meaning:"店舗スペース・商業スペース"},
    {word:"industrial property",meaning:"工業用不動産"},
    {word:"zoning",meaning:"ゾーニング・用途地域指定"},
    {word:"land use",meaning:"土地利用"},
    {word:"building permit",meaning:"建築許可"},
    {word:"occupancy",meaning:"占有・入居率・使用"},
    {word:"vacancy",meaning:"空室・空き・欠員"},
    {word:"lease agreement",meaning:"賃貸契約書"},
    {word:"sublease",meaning:"転貸・サブリース"},
    {word:"assignment of lease",meaning:"賃貸契約の譲渡"},
    {word:"renewal",meaning:"更新・継続・再開"},
    {word:"termination clause",meaning:"解約条項"}
  ],
  "TOEIC_Day08": [
    {word:"英単語",meaning:"和訳"},
    {word:"security deposit",meaning:"敷金・保証金"},
    {word:"key money",meaning:"礼金"},
    {word:"real estate broker",meaning:"不動産仲介業者"},
    {word:"real estate agent",meaning:"不動産エージェント"},
    {word:"brokerage fee",meaning:"仲介手数料"},
    {word:"property appraisal",meaning:"不動産鑑定"},
    {word:"fair market value",meaning:"市場適正価格"},
    {word:"capitalization rate",meaning:"還元利回り"},
    {word:"net operating income",meaning:"純営業収益・NOI"},
    {word:"gross rent",meaning:"総賃料・グロス賃料"},
    {word:"net rent",meaning:"ネット賃料"},
    {word:"rent roll",meaning:"賃料台帳"},
    {word:"property management",meaning:"物件管理"},
    {word:"facilities management",meaning:"施設管理・FM"},
    {word:"renovation work",meaning:"改装工事・リノベーション"},
    {word:"refurbishment",meaning:"改修・修繕"},
    {word:"fit-out",meaning:"内装工事・フィットアウト"},
    {word:"floor plan",meaning:"間取り・平面図"},
    {word:"blueprint",meaning:"設計図・青写真"},
    {word:"tender",meaning:"入札・見積もり依頼"},
    {word:"bid",meaning:"入札・入札する"},
    {word:"scope of work",meaning:"作業範囲・業務内容"},
    {word:"construction",meaning:"建設・建築・工事"},
    {word:"demolition",meaning:"解体・取り壊し"},
    {word:"foundation",meaning:"基礎・財団・設立"},
    {word:"structure",meaning:"構造・建物・仕組み"},
    {word:"HVAC",meaning:"空調設備・暖冷房換気"},
    {word:"elevator",meaning:"エレベーター・昇降機"},
    {word:"escalator",meaning:"エスカレーター"},
    {word:"lobby",meaning:"ロビー・玄関ホール"},
    {word:"reception",meaning:"受付・レセプション"},
    {word:"conference room",meaning:"会議室"},
    {word:"boardroom",meaning:"役員室・会議室"},
    {word:"open plan",meaning:"オープンプラン・フリーアドレス"},
    {word:"hot desking",meaning:"ホットデスキング"},
    {word:"coworking space",meaning:"コワーキングスペース"},
    {word:"serviced office",meaning:"サービスオフィス"},
    {word:"virtual office",meaning:"バーチャルオフィス"},
    {word:"parking",meaning:"駐車場・駐車"},
    {word:"accessibility",meaning:"アクセシビリティ・使いやすさ"},
    {word:"fire safety",meaning:"消防安全"},
    {word:"emergency exit",meaning:"非常口"},
    {word:"evacuation",meaning:"避難・退避"},
    {word:"security",meaning:"セキュリティ・安全・警備"},
    {word:"access control",meaning:"アクセス制御・入退管理"},
    {word:"CCTV",meaning:"防犯カメラ・監視カメラ"},
    {word:"signage",meaning:"看板・サイン・表示"},
    {word:"green building",meaning:"環境配慮型建物"},
    {word:"energy efficiency",meaning:"エネルギー効率"},
    {word:"solar panel",meaning:"太陽光パネル"},
    {word:"renewable energy",meaning:"再生可能エネルギー"},
    {word:"carbon neutral",meaning:"カーボンニュートラル"},
    {word:"smart building",meaning:"スマートビル"},
    {word:"IoT",meaning:"モノのインターネット"},
    {word:"building automation",meaning:"ビルオートメーション"},
    {word:"predictive maintenance",meaning:"予知保全"},
    {word:"condition monitoring",meaning:"状態監視"},
    {word:"asset management",meaning:"資産管理"},
    {word:"LEED certification",meaning:"LEED認証"},
    {word:"title deed",meaning:"権利証書・所有権証書"},
    {word:"encumbrance",meaning:"担保・権利負担"},
    {word:"lien",meaning:"先取特権・抵当権"},
    {word:"covenant",meaning:"契約条項・誓約"},
    {word:"easement",meaning:"地役権"},
    {word:"right of way",meaning:"通行権"},
    {word:"due diligence report",meaning:"デューデリジェンスレポート"},
    {word:"property inspection",meaning:"物件検査"},
    {word:"survey report",meaning:"調査報告書"},
    {word:"planning permission",meaning:"建築確認・開発許可"},
    {word:"environmental assessment",meaning:"環境評価"},
    {word:"soil contamination",meaning:"土壌汚染"},
    {word:"asbestos survey",meaning:"アスベスト調査"},
    {word:"structural survey",meaning:"構造調査"},
    {word:"valuation report",meaning:"評価報告書"},
    {word:"market appraisal",meaning:"市場評価"},
    {word:"capital expenditure",meaning:"設備投資・資本的支出"},
    {word:"operating expenditure",meaning:"運営費・運転費"},
    {word:"return on investment",meaning:"投資収益率"},
    {word:"business travel",meaning:"出張・ビジネストラベル"},
    {word:"travel policy",meaning:"出張規定・旅費規定"},
    {word:"per diem",meaning:"日当・出張手当"},
    {word:"expense report",meaning:"経費精算書・出張報告書"},
    {word:"travel agency",meaning:"旅行代理店"},
    {word:"booking",meaning:"予約・ブッキング"},
    {word:"cancellation",meaning:"キャンセル・取り消し"},
    {word:"itinerary schedule",meaning:"旅程・日程表"},
    {word:"boarding pass",meaning:"搭乗券"},
    {word:"check-in",meaning:"チェックイン"},
    {word:"check-out",meaning:"チェックアウト"},
    {word:"baggage",meaning:"手荷物・荷物"},
    {word:"carry-on luggage",meaning:"機内持ち込み手荷物"},
    {word:"checked baggage",meaning:"預け入れ手荷物"},
    {word:"overweight baggage",meaning:"超過手荷物"},
    {word:"flight",meaning:"フライト・便・飛行"},
    {word:"connection flight",meaning:"乗り継ぎ便"},
    {word:"layover",meaning:"乗り継ぎ待ち・中間寄港"},
    {word:"departure",meaning:"出発・退去"},
    {word:"arrival",meaning:"到着・到来"},
    {word:"delay",meaning:"遅延・遅らせる"},
    {word:"cancellation fee",meaning:"キャンセル料"}
  ],
  "TOEIC_Day11": [
    {word:"英単語",meaning:"和訳"},
    {word:"short position",meaning:"ショートポジション・売り持ち"},
    {word:"day trading",meaning:"デイトレード・日計り取引"},
    {word:"algorithmic trading",meaning:"アルゴリズム取引"},
    {word:"high-frequency trading",meaning:"高頻度取引・HFT"},
    {word:"robo-advisor",meaning:"ロボアドバイザー"},
    {word:"fintech",meaning:"フィンテック・金融テクノロジー"},
    {word:"blockchain",meaning:"ブロックチェーン"},
    {word:"cryptocurrency",meaning:"暗号資産・仮想通貨"},
    {word:"digital currency",meaning:"デジタル通貨"},
    {word:"CBDC",meaning:"中央銀行デジタル通貨"},
    {word:"Sharpe ratio",meaning:"シャープレシオ"},
    {word:"alpha",meaning:"アルファ・超過収益"},
    {word:"beta",meaning:"ベータ・市場連動性"},
    {word:"correlation",meaning:"相関・相関係数"},
    {word:"standard deviation",meaning:"標準偏差"},
    {word:"variance",meaning:"分散・変動"},
    {word:"regression analysis",meaning:"回帰分析"},
    {word:"sensitivity analysis",meaning:"感度分析"},
    {word:"scenario analysis",meaning:"シナリオ分析"},
    {word:"stress test",meaning:"ストレステスト"},
    {word:"value at risk",meaning:"バリューアットリスク・VaR"},
    {word:"risk-adjusted return",meaning:"リスク調整後リターン"},
    {word:"portfolio management",meaning:"ポートフォリオ管理"},
    {word:"fund manager",meaning:"ファンドマネージャー"},
    {word:"mutual fund",meaning:"投資信託・ミューチュアルファンド"},
    {word:"hedge fund",meaning:"ヘッジファンド"},
    {word:"index fund",meaning:"インデックスファンド"},
    {word:"ETF",meaning:"上場投資信託"},
    {word:"pension fund",meaning:"年金基金"},
    {word:"sovereign wealth fund",meaning:"政府系ファンド・SWF"},
    {word:"endowment fund",meaning:"基金・寄付基金"},
    {word:"private placement",meaning:"私募・プライベートプレースメント"},
    {word:"rights issue",meaning:"増資・株主割当発行"},
    {word:"convertible bond",meaning:"転換社債"},
    {word:"preference share",meaning:"優先株"},
    {word:"ordinary share",meaning:"普通株"},
    {word:"authorized capital",meaning:"授権資本"},
    {word:"issued capital",meaning:"発行済資本"},
    {word:"paid-up capital",meaning:"払込資本"},
    {word:"book value",meaning:"簿価・帳簿価額"},
    {word:"market capitalization",meaning:"時価総額"},
    {word:"enterprise value",meaning:"企業価値"},
    {word:"price-earnings ratio",meaning:"株価収益率・PER"},
    {word:"price-to-book ratio",meaning:"株価純資産倍率・PBR"},
    {word:"earnings per share",meaning:"一株当たり利益・EPS"},
    {word:"dividend yield",meaning:"配当利回り"},
    {word:"return on equity",meaning:"自己資本利益率・ROE"},
    {word:"return on assets",meaning:"総資産利益率・ROA"},
    {word:"debt-to-equity ratio",meaning:"負債資本比率"},
    {word:"current ratio",meaning:"流動比率"},
    {word:"quick ratio",meaning:"当座比率"},
    {word:"interest coverage ratio",meaning:"インタレストカバレッジレシオ"},
    {word:"gross profit margin",meaning:"売上総利益率"},
    {word:"operating profit margin",meaning:"営業利益率"},
    {word:"net profit margin",meaning:"純利益率"},
    {word:"EBITDA",meaning:"利払い・税引き・減価償却前利益"},
    {word:"free cash flow",meaning:"フリーキャッシュフロー"},
    {word:"working capital ratio",meaning:"運転資本比率"},
    {word:"asset turnover",meaning:"資産回転率"},
    {word:"inventory turnover",meaning:"在庫回転率"},
    {word:"receivables turnover",meaning:"売掛金回転率"},
    {word:"payables turnover",meaning:"買掛金回転率"},
    {word:"cash conversion cycle",meaning:"キャッシュコンバージョンサイクル"},
    {word:"artificial intelligence",meaning:"人工知能・AI"},
    {word:"machine learning",meaning:"機械学習"},
    {word:"deep learning",meaning:"ディープラーニング"},
    {word:"neural network",meaning:"ニューラルネットワーク"},
    {word:"natural language processing",meaning:"自然言語処理・NLP"},
    {word:"computer vision",meaning:"コンピュータービジョン"},
    {word:"data science",meaning:"データサイエンス"},
    {word:"big data",meaning:"ビッグデータ"},
    {word:"data analytics",meaning:"データ分析・アナリティクス"},
    {word:"edge computing",meaning:"エッジコンピューティング"},
    {word:"Internet of Things",meaning:"モノのインターネット・IoT"},
    {word:"5G network",meaning:"第5世代移動通信・5G"},
    {word:"cybersecurity threat",meaning:"サイバーセキュリティ脅威"},
    {word:"VPN",meaning:"仮想プライベートネットワーク"},
    {word:"two-factor authentication",meaning:"二段階認証"},
    {word:"single sign-on",meaning:"シングルサインオン・SSO"},
    {word:"API",meaning:"アプリケーションプログラミングインターフェース"},
    {word:"microservices",meaning:"マイクロサービス"},
    {word:"DevOps",meaning:"デブオプス・開発運用"},
    {word:"agile development",meaning:"アジャイル開発"},
    {word:"sprint",meaning:"スプリント・開発期間"},
    {word:"user story",meaning:"ユーザーストーリー"},
    {word:"backlog",meaning:"バックログ・積み残し作業"},
    {word:"continuous integration",meaning:"継続的インテグレーション・CI"},
    {word:"continuous deployment",meaning:"継続的デプロイメント・CD"},
    {word:"version control",meaning:"バージョン管理"},
    {word:"repository",meaning:"リポジトリ・コード保管庫"},
    {word:"open source",meaning:"オープンソース"},
    {word:"software development lifecycle",meaning:"ソフトウェア開発ライフサイクル"},
    {word:"user experience",meaning:"ユーザーエクスペリエンス・UX"},
    {word:"user interface",meaning:"ユーザーインターフェース・UI"},
    {word:"responsive design",meaning:"レスポンシブデザイン"},
    {word:"usability",meaning:"ユーザビリティ・使い勝手"},
    {word:"wireframe",meaning:"ワイヤーフレーム・設計図"},
    {word:"mockup",meaning:"モックアップ・試作品"},
    {word:"user testing",meaning:"ユーザーテスト"},
    {word:"debugging",meaning:"デバッグ・バグ修正"}
  ],
  "TOEIC_Day17": [
    {word:"英単語",meaning:"和訳"},
    {word:"eco-design",meaning:"エコデザイン・環境配慮設計"},
    {word:"cradle-to-cradle",meaning:"ゆりかごからゆりかごへ"},
    {word:"SDGs",meaning:"持続可能な開発目標"},
    {word:"social enterprise",meaning:"ソーシャルエンタープライズ"},
    {word:"B corporation",meaning:"Bコープ・社会的企業認証"},
    {word:"shared value",meaning:"共有価値"},
    {word:"blended finance",meaning:"ブレンデッドファイナンス"},
    {word:"green finance",meaning:"グリーンファイナンス"},
    {word:"environmental compliance",meaning:"環境法令遵守"},
    {word:"ecological footprint",meaning:"エコロジカルフットプリント"},
    {word:"natural capital",meaning:"自然資本"},
    {word:"ecosystem restoration",meaning:"生態系回復"},
    {word:"net positive impact",meaning:"ネットポジティブインパクト"},
    {word:"scope of emissions",meaning:"排出範囲"},
    {word:"science-based targets",meaning:"科学的根拠に基づく目標"},
    {word:"SBTi",meaning:"科学的根拠に基づく目標イニシアチブ"},
    {word:"GHG protocol",meaning:"GHGプロトコル"},
    {word:"sustainability strategy",meaning:"サステナビリティ戦略"},
    {word:"ESG due diligence",meaning:"ESGデューデリジェンス"},
    {word:"ESG reporting",meaning:"ESGレポーティング"},
    {word:"responsible investment",meaning:"責任ある投資"},
    {word:"green procurement",meaning:"グリーン調達"},
    {word:"sustainable supply chain",meaning:"持続可能なサプライチェーン"},
    {word:"global business",meaning:"グローバルビジネス"},
    {word:"multinational corporation",meaning:"多国籍企業・MNC"},
    {word:"foreign direct investment",meaning:"外国直接投資・FDI"},
    {word:"joint venture agreement",meaning:"合弁事業契約"},
    {word:"strategic alliance agreement",meaning:"戦略的提携協定"},
    {word:"licensing deal",meaning:"ライセンス取引"},
    {word:"export strategy",meaning:"輸出戦略"},
    {word:"import regulation",meaning:"輸入規制"},
    {word:"trade barrier",meaning:"貿易障壁"},
    {word:"non-tariff barrier",meaning:"非関税障壁"},
    {word:"protectionism",meaning:"保護主義"},
    {word:"free trade agreement",meaning:"自由貿易協定・FTA"},
    {word:"World Trade Organization",meaning:"世界貿易機関・WTO"},
    {word:"globalization",meaning:"グローバリゼーション"},
    {word:"localization strategy",meaning:"ローカライゼーション戦略"},
    {word:"glocalization",meaning:"グローカリゼーション"},
    {word:"cultural intelligence",meaning:"文化的知性・CQ"},
    {word:"cultural adaptation",meaning:"文化的適応"},
    {word:"cross-cultural communication",meaning:"異文化間コミュニケーション"},
    {word:"language barrier",meaning:"言語障壁"},
    {word:"translation service",meaning:"翻訳サービス"},
    {word:"interpretation service",meaning:"通訳サービス"},
    {word:"expatriate management",meaning:"駐在員管理"},
    {word:"global mobility",meaning:"グローバルモビリティ"},
    {word:"repatriation support",meaning:"帰任支援"},
    {word:"work permit",meaning:"就労許可証"},
    {word:"immigration compliance",meaning:"入国管理法令遵守"},
    {word:"tax treaty",meaning:"租税条約"},
    {word:"transfer pricing",meaning:"移転価格"},
    {word:"arm's length principle",meaning:"独立企業原則"},
    {word:"permanent establishment",meaning:"恒久的施設・PE"},
    {word:"double taxation avoidance",meaning:"二重課税防止"},
    {word:"profit repatriation",meaning:"利益の本国送還"},
    {word:"political risk insurance",meaning:"政治的リスク保険"},
    {word:"country risk rating",meaning:"国リスク格付け"},
    {word:"sovereign risk",meaning:"ソブリンリスク"},
    {word:"emerging market",meaning:"新興市場"},
    {word:"developed market",meaning:"先進市場"},
    {word:"frontier market",meaning:"フロンティア市場"},
    {word:"BRICS",meaning:"ブリックス"},
    {word:"G7 summit",meaning:"G7サミット"},
    {word:"G20 meeting",meaning:"G20会合"},
    {word:"ASEAN",meaning:"東南アジア諸国連合"},
    {word:"European Union",meaning:"欧州連合・EU"},
    {word:"Brexit impact",meaning:"ブレグジットの影響"},
    {word:"trade war",meaning:"貿易戦争"},
    {word:"economic sanctions",meaning:"経済制裁"},
    {word:"export control compliance",meaning:"輸出管理コンプライアンス"},
    {word:"dual-use goods",meaning:"デュアルユース品"},
    {word:"anti-dumping measure",meaning:"アンチダンピング措置"},
    {word:"countervailing duties",meaning:"相殺関税"},
    {word:"rules of origin",meaning:"原産地規則"},
    {word:"harmonized system code",meaning:"HS分類コード"},
    {word:"customs documentation",meaning:"税関書類"},
    {word:"documentary letter of credit",meaning:"荷為替信用状"},
    {word:"open account",meaning:"オープンアカウント取引"},
    {word:"international wire transfer",meaning:"国際電信送金"},
    {word:"SWIFT code",meaning:"SWIFTコード"},
    {word:"IBAN",meaning:"国際銀行口座番号"},
    {word:"foreign currency account",meaning:"外貨預金口座"},
    {word:"cross-border payment",meaning:"クロスボーダー決済"},
    {word:"trade finance",meaning:"貿易金融"},
    {word:"export credit",meaning:"輸出信用"},
    {word:"export credit agency",meaning:"輸出信用機関"},
    {word:"IFRS compliance",meaning:"IFRS準拠"},
    {word:"GAAP reconciliation",meaning:"GAAP調整"},
    {word:"consolidated financial statements",meaning:"連結財務諸表"},
    {word:"segment reporting",meaning:"セグメント報告"},
    {word:"foreign currency translation",meaning:"外貨換算"},
    {word:"hedging strategy",meaning:"ヘッジング戦略"},
    {word:"currency forward",meaning:"為替先物"},
    {word:"natural hedging",meaning:"ナチュラルヘッジ"},
    {word:"international tax planning",meaning:"国際税務計画"},
    {word:"base erosion",meaning:"税源浸食"},
    {word:"profit shifting",meaning:"利益移転"},
    {word:"BEPS",meaning:"税源浸食と利益移転"},
    {word:"country-by-country reporting",meaning:"国別報告書"}
  ],
  "TOEIC_Day12": [
    {word:"英単語",meaning:"和訳"},
    {word:"quality assurance testing",meaning:"品質保証テスト"},
    {word:"rollback",meaning:"ロールバック・元に戻す"},
    {word:"uptime",meaning:"アップタイム・稼働時間"},
    {word:"server load",meaning:"サーバー負荷"},
    {word:"performance optimization",meaning:"パフォーマンス最適化"},
    {word:"latency",meaning:"レイテンシー・遅延"},
    {word:"throughput",meaning:"スループット・処理能力"},
    {word:"data center",meaning:"データセンター"},
    {word:"virtual machine",meaning:"仮想マシン・VM"},
    {word:"containerization",meaning:"コンテナ化"},
    {word:"Docker",meaning:"ドッカー・コンテナプラットフォーム"},
    {word:"Kubernetes",meaning:"クーベルネティス・コンテナ管理"},
    {word:"serverless",meaning:"サーバーレス"},
    {word:"Infrastructure as Code",meaning:"コードによるインフラ管理"},
    {word:"data migration",meaning:"データ移行"},
    {word:"legacy system",meaning:"レガシーシステム"},
    {word:"system integration",meaning:"システム統合"},
    {word:"middleware",meaning:"ミドルウェア"},
    {word:"database management",meaning:"データベース管理"},
    {word:"SQL",meaning:"構造化照会言語"},
    {word:"NoSQL",meaning:"非リレーショナルデータベース"},
    {word:"data warehouse",meaning:"データウェアハウス"},
    {word:"data lake",meaning:"データレイク"},
    {word:"ETL process",meaning:"抽出・変換・ロード"},
    {word:"visualization",meaning:"可視化・ビジュアライゼーション"},
    {word:"real-time analytics",meaning:"リアルタイム分析"},
    {word:"predictive analytics",meaning:"予測分析"},
    {word:"prescriptive analytics",meaning:"処方的分析"},
    {word:"startup",meaning:"スタートアップ・新興企業"},
    {word:"unicorn",meaning:"ユニコーン・高評価スタートアップ"},
    {word:"pivot",meaning:"ピボット・方向転換"},
    {word:"incubator",meaning:"インキュベーター・起業支援機関"},
    {word:"accelerator",meaning:"アクセラレーター・起業加速支援"},
    {word:"minimum viable product",meaning:"最小実用製品・MVP"},
    {word:"product-market fit",meaning:"プロダクトマーケットフィット"},
    {word:"growth hacking",meaning:"グロースハッキング"},
    {word:"viral loop",meaning:"バイラルループ"},
    {word:"network effect",meaning:"ネットワーク効果"},
    {word:"platform economy",meaning:"プラットフォーム経済"},
    {word:"sharing economy",meaning:"シェアリングエコノミー"},
    {word:"gig economy",meaning:"ギグエコノミー"},
    {word:"subscription economy",meaning:"サブスクリプション経済"},
    {word:"marketplace",meaning:"マーケットプレイス・取引所"},
    {word:"two-sided market",meaning:"二面市場"},
    {word:"aggregator",meaning:"アグリゲーター・仲介サービス"},
    {word:"open innovation",meaning:"オープンイノベーション"},
    {word:"co-creation",meaning:"共創・コクリエーション"},
    {word:"crowdsourcing",meaning:"クラウドソーシング"},
    {word:"hackathon",meaning:"ハッカソン"},
    {word:"innovation lab",meaning:"イノベーションラボ"},
    {word:"intrapreneurship",meaning:"社内起業家精神"},
    {word:"corporate venturing",meaning:"コーポレートベンチャリング"},
    {word:"digital ethics",meaning:"デジタル倫理"},
    {word:"algorithmic bias",meaning:"アルゴリズムバイアス"},
    {word:"responsible AI",meaning:"責任あるAI"},
    {word:"AI governance",meaning:"AIガバナンス"},
    {word:"explainable AI",meaning:"説明可能なAI・XAI"},
    {word:"federated learning",meaning:"連合学習"},
    {word:"edge AI",meaning:"エッジAI"},
    {word:"cyber resilience",meaning:"サイバーレジリエンス"},
    {word:"zero trust security",meaning:"ゼロトラストセキュリティ"},
    {word:"customer service",meaning:"顧客サービス・カスタマーサービス"},
    {word:"customer support",meaning:"カスタマーサポート"},
    {word:"helpdesk",meaning:"ヘルプデスク・問い合わせ窓口"},
    {word:"call center",meaning:"コールセンター"},
    {word:"contact center",meaning:"コンタクトセンター"},
    {word:"support ticket",meaning:"サポートチケット・問い合わせ票"},
    {word:"inquiry",meaning:"問い合わせ・照会"},
    {word:"complaint",meaning:"苦情・クレーム"},
    {word:"escalation",meaning:"エスカレーション・上位対応"},
    {word:"SLA",meaning:"サービスレベル協定"},
    {word:"response time",meaning:"応答時間・対応時間"},
    {word:"first contact resolution",meaning:"初回対応解決率"},
    {word:"customer retention",meaning:"顧客維持・定着"},
    {word:"churn",meaning:"解約・離脱"},
    {word:"customer effort score",meaning:"顧客努力指数・CES"},
    {word:"customer satisfaction score",meaning:"顧客満足スコア・CSAT"},
    {word:"review",meaning:"レビュー・評価・見直す"},
    {word:"rating",meaning:"評価・格付け"},
    {word:"return policy",meaning:"返品ポリシー"},
    {word:"terms of service",meaning:"利用規約"},
    {word:"cookie policy",meaning:"クッキーポリシー"},
    {word:"opt-in",meaning:"オプトイン・同意"},
    {word:"opt-out",meaning:"オプトアウト・同意撤回"},
    {word:"consent",meaning:"同意・承諾"},
    {word:"recommendation",meaning:"推奨・リコメンデーション"},
    {word:"chatbot",meaning:"チャットボット"},
    {word:"virtual assistant",meaning:"バーチャルアシスタント"},
    {word:"FAQ",meaning:"よくある質問"},
    {word:"knowledge base",meaning:"ナレッジベース"},
    {word:"self-service portal",meaning:"セルフサービスポータル"},
    {word:"customer portal",meaning:"顧客ポータル"},
    {word:"omnichannel",meaning:"オムニチャネル"},
    {word:"multichannel",meaning:"マルチチャネル"},
    {word:"social media support",meaning:"ソーシャルメディアサポート"},
    {word:"live chat",meaning:"ライブチャット"},
    {word:"email support",meaning:"メールサポート"},
    {word:"phone support",meaning:"電話サポート"},
    {word:"remote support",meaning:"リモートサポート"},
    {word:"on-site support",meaning:"現地サポート"}
  ]
};
